### ISSUE TITLE
[Suggestion] Config for Disabling Blocks/Items

### ISSUE THREAD

**Issue by davqvist** [MinecraftModDevelopmentMods/BaseMetals#103]
I wonder if you could add a config like most mods do to disable blocks/items being registered. I'm working on a modpack and I had to use Crafttweaker to disable all of them and the JEI hide feature to hide them. Besides being a lot of work, the real problem is though that the integration of other mods add the items for more recipes mostly because of Ore Dictionary. So I have to disable those recipes as well, but some don't offer Crafttweaker/Modtweaker support which means I have to remove the items from the Ore Dictionary which sometimes doesn't work because removing them after the fact is too late or has other unwanted side effects I don't want to be happening.

That's why a config for that would be nice. A config to enable/disable every item seperatably is probably not needed, but being able to disable all items from one ore and to disable all items from a type (ingots/plates/gears etc) would be very helpful. Same config option for Modern Metals would be awesome.

Thanks in advance.

**Comment by dshadowwolf** [comment]
This is already available in the dev versions and will be available when 2.5 is released. Right now exactly what you've requested is what the dev versions have and there are some plans to make it so individual items can be disabled in a later version.

**Comment by davqvist** [comment]
This is awesome. Thanks a lot.
