### ISSUE TITLE
[Bug] Redstone get dustQuartz oreDict name

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/BaseMetals#158]
Don't know why, but if I remove ALT, OreSpawn and BaseMetal, redstone dust no longer is registered in dustQuartz

MC 1.11.2
Forge 2393
ALT 2.0.1.14
OS 3.0.0.36
BaseMetals 2.5.0-beta1.45
[Full modList](https://pastebin.com/V1C68xLL)

**Comment by dshadowwolf** [comment]
This is, sadly, a known bug that I thought had been squashed a while back (like, in the 1.10.2 tree) apparently the fix did not carry over - should be fixed in the next beta, but I'll double check.

**Comment by drakray** [comment]
setting 
`# Enable Nether Quartz Items and Materials (not currently in use) [default: true]
B:EnableQuartz=false`
`# Enable Redstone Items and Materials (not currently in use) [default: true]
B:EnableRedstone=false`
apparently tempFix it

**Comment by dshadowwolf** [comment]
Is this still active in the current releases or even maven code ?

**Comment by dshadowwolf** [comment]
Question repeated: is this still a valid bug or has it finally been squashed ?

**Comment by jriwanek** [comment]
confirmed with MMDLogger to no longer be an issue.
