### ISSUE TITLE
BaseMetals and SpongeForge server crash

### ISSUE THREAD

**Issue by BakermanLP** [MinecraftModDevelopmentMods/BaseMetals#159]
Hello,
I am trying to build a modpack. For the server part I want to include spongeforge. But with BaseMetals the server crashes with a Mixin error.

The complete startup logfile can be found here: 
http://paste.ubuntu.com/25131722/

Used versions:
Minecraft 1.11.2
forge-1.11.2-13.20.1.2393-universal.jar
mods/spongeforge-1.11.2-2393-6.1.0-BETA-2471.jar
mods/BaseMetals-1.11.2-2.5.0-beta2.73.jar

Just to say, if I remove BaseMetals, the error is gone.

Can you fix that?

Thanks for reading

Michael (aka BakermanLP)

**Comment by dshadowwolf** [comment]
At this time we do not test again Sponge and there is an ASM transformer and an ASM-based plugin loader in BaseMetals. Though BaseMetals ASM does not touch blocks (at least, the part I know of and have worked on is only for horse-armor) the base mod itself references net.minecraft.block.Blocks statically in a few places.

I am loathe to say it, but at this time none of the *metals mods are compatible with Sponge. This might be easily resolved and will be looked into later.

**Comment by ryantheleach** [comment]
It's not a matter of being compatible with Sponge, but that loading *any* classes that early will result in conflicts with other mods performing transformations after yours.

**Comment by dshadowwolf** [comment]
huh ? Nothing should be touched until Forge PreInit, when the mod actually starts creating blocks and items, like every other mod out there. Please, regale me with your wondrous insight that makes doing things properly and in the same manner as every other mod an issue.

**Comment by simon816** [comment]
@dshadowwolf Your `ASMTransformer` [classloads `Platform`](https://github.com/MinecraftModDevelopmentMods/BaseMetals/blob/4275aa82cbcce14c3c7f4ad663fd0771c692331a/src/main/java/com/mcmoddev/lib/asm/ASMTransformer.java#L36) (also [here](https://github.com/MinecraftModDevelopmentMods/BaseMetals/blob/4275aa82cbcce14c3c7f4ad663fd0771c692331a/src/main/java/com/mcmoddev/lib/asm/ASMPlugin.java#L46)) through the wrong classloader, normal mod classes should go through `LaunchClassLoader`.

`Platform` loads (among other things) [`ItemStack`](https://github.com/MinecraftModDevelopmentMods/BaseMetals/blob/4275aa82cbcce14c3c7f4ad663fd0771c692331a/src/main/java/com/mcmoddev/lib/util/Platform.java#L48), which in turn loads other classes such as `Block` (e.g. the `ItemStack` constructor `public ItemStack(Block blockIn)`).

You're also potentially [classloading `BaseMetals`](https://github.com/MinecraftModDevelopmentMods/BaseMetals/blob/4275aa82cbcce14c3c7f4ad663fd0771c692331a/src/main/java/com/mcmoddev/lib/asm/ASMTransformer.java#L48) under certain conditions.

It is highly recommended to keep coremod components separated from normal mod classes as much as possible, it helps to avoid these situations (forge is getting more strict about this).
I suggest sharing information through designated classes that do not load minecraft-related classes, you can even use the `Launch.blackboard` for this purpose.

**Comment by dshadowwolf** [comment]
This is information I did not know. All I've done with that code is to get it working on 1.11 - which was a bit of a pain because the original version was apparently badly broken.

With this code, though, it is running in the right class, and the Platform use itself can likely go away, as it is being used solely to detect whether the code is loading in dev and that is not, at the current time, actually supported by the currently running version of the code.

I'll need to discuss this with @jriwanek and also with @pau101, who helped me figure out what the issue was that was stopping the code from working in the first place.

**Comment by arronm** [comment]
I am also seeing issues with this causing sponge launch to crash while only SpongeForge and BaseMetals are being loaded.

**Comment by bookerthegeek** [comment]
## Heyo
Was going to include the MMD mods in my pack, alas this issue came up.
```
[00:36:10] [main/INFO] [Sponge]: /*                                                                                                                                                                            */
[00:36:10] [main/INFO] [Sponge]: /* An essential class was loaded before Sponge could patch it, this usually means                                                                                             */
[00:36:10] [main/INFO] [Sponge]: /* that another coremod has caused the class to load prematurely.                                                                                                             */
[00:36:10] [main/INFO] [Sponge]: /*                                                                                                                                                                            */
[00:36:10] [main/INFO] [Sponge]: /*           Class Name : net.minecraftforge.fml.common.ModContainer                                                                                                          */
[00:36:10] [main/INFO] [Sponge]: /*                                                                                                                                                                            */

```
Any idea on if this will be resolved soon as with it currently being incompatible with SpongeForge this makes it unable to be used on many a server.

**Comment by dshadowwolf** [comment]
Yes. It seems that our use of "Platform" in the checks as to whether some of our ASM gets used or not is causing issues with Sponge. As there is currently only one person on the MMD Team that knows anything, really, about ASM and the deep magic there - and they are not on the *Metals team - I cannot say when this bug will be addressed.

**Comment by dshadowwolf** [comment]
The latest PR (#412) from me fixes this issue by removing the CoreMod entirely, as the classloading issue proved to be... outside the skill of any of the team to fix and maintain existing functionality. The issue was not with any Minecraft class, in the end, but with Forge classes. Our ASM plugin system would check the version of Forge it was running on to know whether or not to actually load, as Forge gained a form of the hooks we used for Horse Armor during the 1.12 release cycle. This referencing of ``ForgeVersion`` caused ``ModContainer`` to be loaded early, causing Sponge to not be able to apply its mixins to that class.

When the PR (which does a lot more) is merged, this should finally be resolved and able to be closed for good.

**Comment by dshadowwolf** [comment]
Fix is now available, in -dev, as beta6.308 - you can get the mod [here](https://maven.mcmoddev.com/com/mcmoddev/BaseMetals/1.12-2.5.0-beta6.308/BaseMetals-1.12-2.5.0-beta6.308.jar) -- or if you'd like to see all the build artifacts and get it yourself, see [here](https://maven.mcmoddev.com/com/mcmoddev/BaseMetals/1.12-2.5.0-beta6.308/)

Closing as fixed (finally)

**Comment by dshadowwolf** [comment]
Final note: This fixed version requires, at a minimum, Forge 14.23.1.2592 - this is because that is the first version where adding new Horse Armor does not require a core-mod.

**Comment by bookerthegeek** [comment]
Thank you!

**Comment by dshadowwolf** [comment]
No problem - took a bit of programmer conversation to figure things out. Oh, and that version is not just the fix for the Sponge issue - it also contains a preliminary (sometimes a little broken - in a "what aspects show" and not a "will crash on you" way) version of Thaumcraft 6 integration

**Comment by bookerthegeek** [comment]
Would you be able to also update the rest of the Family of mods also please? Or would a new issue for each be better?

**Comment by jriwanek** [comment]
For thaumcraft or the sponge fix?

**Comment by bookerthegeek** [comment]
The Sponge Fix

**Comment by jriwanek** [comment]
Use em with updated BaseMetals, they'll automatically get it. Tis the wonderful thing about shared code.

**Comment by dshadowwolf** [comment]
:man_facepalming: Keep an eye on the Maven - I'd forgotten we'd had a major cleanup that moved some things around. Updates in the places that need them are coming.
