### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sninctbur** [MinecraftModDevelopmentMods/BaseMetals#161]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.11.2.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  PotionCoreFMLLoadingPlugin (PotionCore-1.4.1_for_1.11.2.jar)
  CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.3.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.7.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/26/17 6:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Base Metals (basemetals)
Caused by: java.lang.NullPointerException
	at com.mcmoddev.basemetals.init.Achievements.init(Achievements.java:36)
	at com.mcmoddev.basemetals.proxy.CommonProxy.init(CommonProxy.java:70)
	at com.mcmoddev.basemetals.proxy.ClientProxy.init(ClientProxy.java:63)
	at com.mcmoddev.basemetals.BaseMetals.init(BaseMetals.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 247490080 bytes (236 MB) / 660717568 bytes (630 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 Optifine OptiFine_1.11.2_HD_U_C3 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCHI	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCHI	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHI	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCHI	potioncore_coremod{1.4.1_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHI	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHI	quark{r1.2-93} [Quark] (Quark-r1.2-93.jar) 
	UCHI	animania{1.2.1} [Animania] (animania-1.11.2-1.2.1.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHE	basemetals{2.5.0-beta1} [Base Metals] (BaseMetals-1.11.2-2.5.0-beta1.45.jar) 
	UCHI	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.3.jar) 
	UCHI	mujmajnkraftsbettersurvival{1.2.1} [Better Survival] (BetterSurvival-1.2.1.jar) 
	UCHI	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.1.0.jar) 
	UCHI	biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
	UCHI	bullseye{2.0.0} [Bullseye] (Bullseye-1.11.2-2.0.0.jar) 
	UCHI	compot{1.0} [Combined Potions] (CombinedPotions-1.11-1.0.jar) 
	UCHI	csaddle{1.2} [Craftable Saddles] (Craftable Saddles- MC1.11.jar) 
	UCHI	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.4 mc1.11.2.jar) 
	UCHI	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot 1.11.2 (v.1.0.1).jar) 
	UCHI	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.1-MC1.11.2.jar) 
	UCHI	dungeontactics{DT-0.12.3} [DungeonTactics] (DungeonTactics-1.11.2-0.12.3.jar) 
	UCHI	dsurround{3.4.5.7} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.7.jar) 
	UCHI	presets{3.4.5.7} [Presets!] (DynamicSurroundings-1.11.2-3.4.5.7.jar) 
	UCHI	emvi{2.2} [Emergent Villages] (EmergentVillages-2.2.jar) 
	UCHI	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.1.2 mc1.11.2.jar) 
	UCHI	epicsiegemod{12.0.158} [Epic Siege Mod] (EpicSiegeMod-12.0.158.jar) 
	UCHI	erosion{1.0} [Erosion] (Erosion-1.0.jar) 
	UCHI	fbp{2.2} [Fancy Block Particles] (FancyBlockParticles-1.11.2-2.2.jar) 
	UCHI	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCHI	felling{1.1} [Felling] (felling-1.1.jar) 
	UCHI	finite-water-control{1.0} [finite-water-control] (finite-water-control-1.11.2-1.0.jar) 
	UCHI	combat{1.0.0} [Gladius] (Gladius-2.0.0.jar) 
	UCHI	iv{2.1.0} [Improved Villagers] (Improved Villagers-2.1.0.jar) 
	UCHI	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCHI	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHI	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHI	magma_monsters{0.2.0} [magma_monsters] (MagmaMonsters-0.2.0.jar) 
	UCHI	mobends{0.23.5} [Mo'Bends] (mobends-0.23.5_for_MC-1.11.2.jar) 
	UCHI	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCHI	nodami{0.2} [No Damage Immunity (NoDamI)] (nodami-1.11.2-0.2.jar) 
	UCHI	potioncore{1.4.1_for_1.11.2} [Potion Core] (PotionCore-1.4.1_for_1.11.2.jar) 
	UCHI	nep{1.3_for_1.11.2} [Not Enough Potions] (NotEnoughPotions-1.3_for_1.11.2.jar) 
	UCHI	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.11-1.0.1.jar) 
	UCHI	orespawn{3.0.0} [OreSpawn] (OreSpawn-1.11.2-3.0.0.36.jar) 
	UCHI	reforged{0.7.4} [Reforged] (Reforged-0.7.4-1.11+.jar) 
	UCHI	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-67.jar) 
	UCHI	ropebridge{1.4.8} [Rope Bridge] (ropebridge-1.11.2-1.4.8.jar) 
	UCHI	simplecorn{2.2.0} [Simple Corn] (simpleCorn1.11.2-2.2.0.jar) 
	UCHI	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCHI	slurp{0.2} [Slurp] (slurp-1.11.2-0.2.jar) 
	UCHI	sophisticatedwolves{3.8.0} [Sophisticated Wolves] (SophisticatedWolves-1.11.2-3.8.0.jar) 
	UCHI	souls{2.0.0} [Souls] (Souls-1.11.2-2.0.0.jar) 
	UCHI	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCHI	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCHI	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCHI	storageboats{2.0} [Storage Boats Mod] (StorageBoats-2.1.jar) 
	UCHI	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCHI	tanspit{@VERSION@} [Campfire Spit] (tanspit-1.11.2-1.3.jar) 
	UCHI	tumbleweed{1.11-0.3.1} [Tumbleweed] (tumbleweed-1.11-0.3.1.jar) 
	UCHI	vanillafoodplus{1.0.0} [VanillaFoodPlus] (VanillaFoodPlus1.11.2.jar) 
	UCHI	voidfog{1.0.1} [Void Fog] (VoidFog-1.0.1.jar) 
	UCHI	waddles{0.5.2} [Waddles] (Waddles-1.11.2-0.5.2.jar) 
	UCHI	waystones{3.0.13} [Waystones] (Waystones_1.11.2-3.0.13.jar) 
	UCHI	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
	UCHI	witherskelefix{1.6.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.11.2-1.6.3.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.2-93.jar)
  vazkii.quark.base.asm.ClassTransformer
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
PotionCoreFMLLoadingPlugin (PotionCore-1.4.1_for_1.11.2.jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.7.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'

**Comment by dshadowwolf** [comment]
...Do you have the Crackhammer disabled ?

@jriwanek is nominally in charge of this code and I can see that it doesn't seem to check and see if the Crackhammer is enabled or not before trying to initialize an achievement that uses it.

A fix is going in and will, hopefully, be available when we push -beta2

**Comment by Sninctbur** [comment]
Sorry about the late reply. The Crack Hammer is enabled. However, I have disabled a large amount of the included ores; nothing crashed until I did that.

**Comment by dshadowwolf** [comment]
Okay - this is either dying because the "this is new" achievement (based on smelting copper) is coming up null or there is an issue with the crackhammer in the code - and if it was the "this is new" achievement, it would be crashing on line 35, as it is referenced there as well.

Means that there is an issue with the code - likely either BaseMetals is not registering the vanilla material Iron for internal use. That should be changing in -beta2.

**Comment by Sninctbur** [comment]
According to the config file, BaseMetals achievements currently need to be disabled if you disable any ores. That was a step I forgot to take.

**Comment by jriwanek** [comment]
Appears to be resolved, closing unless I here otherwise.
