### ISSUE TITLE
Missing armor textures

### ISSUE THREAD

**Issue by LakMoore** [MinecraftModDevelopmentMods/BaseMetals#163]
Not sure if these are in a to do list somewhere, but I thought a list here might be handy.  The following armors are missing all four textures.

Antimony
Bismuth
Emerald
Obsidian
Pewter
Quartz
Zinc

**Comment by LakMoore** [comment]
I missed one!

Antimony
Bismuth
Emerald
Obsidian
Pewter
Quartz
Zinc

**Comment by dshadowwolf** [comment]
This is, I believe, a known issue and on @jriwanek list, as she's the one in contact with the artist that has done the rest of the textures. Lets put this one on her for now.

**Comment by dshadowwolf** [comment]
#227 fixes this
