### ISSUE TITLE
GUI Texture not working

### ISSUE THREAD

**Issue by LakMoore** [MinecraftModDevelopmentMods/BaseMetals#164]
<img width="1271" alt="minecraft_1_11_2" src="https://user-images.githubusercontent.com/6624290/29489599-b506ee3e-851c-11e7-8740-d459558edf75.png">

Also, the block is not showing on the JEI tab either.

**Comment by dshadowwolf** [comment]
This should be fixed in the current dev tip

**Comment by D3nnis3n** [comment]
Problem still persists for beta.19

**Comment by D3nnis3n** [comment]
This issue is fixed as of the latest Version.
