### ISSUE TITLE
Missing Trapdoor Textures

### ISSUE THREAD

**Issue by LakMoore** [MinecraftModDevelopmentMods/BaseMetals#165]
<img width="357" alt="minecraft_1_11_2" src="https://user-images.githubusercontent.com/6624290/29493283-1f6f2372-858b-11e7-8d66-79082031c30d.png">

Emerald
Obsidian
Quartz

**Comment by dshadowwolf** [comment]
Another known issue, lets put this with the person who is in charge of herding the artists...

**Comment by TheRealDadbeard** [comment]
There are multiple items without a texture mainly obsidian, coal and emerald stuff. Are those bugs or the same issue of missing textures? Didn't want to open a new issue.

**Comment by dshadowwolf** [comment]
Same deal, really... Probably even more in 1.12, too - there maybe be some issues with the code over-generating some items. I haven't had time to look into it yet. Most of the last 2 to 3 weeks has been spent porting MMD OreSpawn, Additional Loot Tables, Base Metals, Modern Metals, Base Minerals and Nether Metals to 1.12 and fleshing out features originally planned for the 1.10 version.

Please bear with me, as right now @jriwanek is having some health issues and @knoxhack is working on several new members of the *Metals family - leaving me to handle bug-fixes and porting all alone. (yes, that is meant to be sarcastic - please laugh at the bad joke)

**Comment by dshadowwolf** [comment]
#227 fixes this
