### ISSUE TITLE
Crash on 1.12.1 with Extra Utilities

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#179]
I'm absoluteley aware the 1.12.1 versions are absoluteley not stable, in development and should not be used by me, nontheless i sneaked to your maven and installed base and modern metals. And it works great!

But, if extrautilities is installed i get the following Crash:

> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
> Caused by: java.lang.NullPointerException
> 	at com.rwtema.extrautils2.modcompat.TinkersIntegration.init(TinkersIntegration.java:282)
> 	at com.rwtema.extrautils2.modcompat.TinkersIntegrationEntry.init(TinkersIntegrationEntry.java:33)
> 	at com.rwtema.extrautils2.backend.entries.EntryHandler.init(EntryHandler.java:81)
> 	at com.rwtema.extrautils2.ExtraUtils2.init(ExtraUtils2.java:151)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
> 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
> 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

If you are already Aware, or this is being caused by the mod extrautils or it's just because it is in heavy development: Please Close and do not care. If you didn't knew about it yet and it's on your side to fix: I hope this Report is fine.

Thanks for your great work for modpackmakers.

If of any interest:
I only saw six or so missing textures and the missing tinkers construct Integration, i can spawn them just right and all recipes are working. JAOPCA is not creating coins out of them, tough. PlusTic also complained because "heavy" was already added as trait. I removed it, as it should no longer be needed after your metals are stable and installed.

**Comment by dshadowwolf** [comment]
I'm actually working in this area right now because of some other pieces being slightly broken.

As to 'heavy' - it might not mean the same thing in PlusTiC as it does in BaseMetals. In BaseMetals it gives additional knockback.

The JAOPCA.... well... don't know there - might be missing an OreDictionary it needs or similar.

(The way we'd been doing Trait registrations was causing some Forge Registry issues, which might have tied into the ExU2 issue in question here, though it might also be the Redstone Ingot or similar)

**Comment by D3nnis3n** [comment]
Oh, i don't really care what "heavy" means with your mod, it's just that many metals did not have any traits until PlusTic - when your metals add traits for the materials that's all i wanted PlusTiC for. 

JAOPCA, i don't really know how they do the Magic, but it works with pretty much any mod that adds ores. It would be great if your metal mods would work too. It only adds things that are not already present - so not another copper plate, but only a copper coin - that's a great concept, i loved AOBD.

For me only the tinkers Integration is missing and the mod would be fully usable. I will follow your development, and if you allow, i would write further bug Reports when i come over something. I'm still fully Aware i'm using heavy in development Software and should at least not use it in productive Environments.

**Comment by dshadowwolf** [comment]
Alright - looks like the *Metals "brittle" is a conflicting name with ExU2. That is triggering the interaction, apparently, so let me go mod the name we use internally. Same for "heavy" - what I'm modifying is an internal name, so hopefully it won't have an effect elsewhere. This way the traits hopefully do not conflict.

**Comment by dshadowwolf** [comment]
Found another issue, thanks to this, that none of our materials are actually registering as usable for tools. I need to explore this more.

**Comment by dshadowwolf** [comment]
Will be making a PR shortly that fixes this - issue went deep into some Tinkers' Construct integration API changes that I had not been aware of prior to your report.

**Comment by D3nnis3n** [comment]
I'm glad that i could help, even though sneak-testing a not published version.
Please take all the time to fix you need, i'm just here to help out - but thanks for the already done fixes. :)

As i saw the BaseMetals Maven Build has been updated, but the ModernMetals one hasn't - is there no Need to update this one, too, as BaseMetals handles all the Magic?

I would try out the new build later this day and report back if i stumble upon anything.

May i at last gently ask if you're planning to release Nether / End Metals with base and modern metals or will that come later / won't come?

Do you think it might be worth opening an issue on JACOPA for the issue with not created coins for your metals? (Not tested if already works now)

**Comment by D3nnis3n** [comment]
I'm happy to tell you that the Crash with PlusTic and the Crash with ExtraUtilities have been resolved.
Also, Tinker's Construct integration is now working. 

The only thing missing are the coins of JAOPCA. I also found that despite you are adding Diamond tools to tinkers construct, Diamonds can not be smelted in the tinkers construct smelter, what causes them to be unavailable. I think this might also be the case with other vanilla ore fluids you add (Lapis? didn't check.). Great Work!

I also do really like how alloying in tinkers is working with your metals. That's so much fun!

**Comment by dshadowwolf** [comment]
There is a __LOT__ of magic that happens in BaseMetals, yes. That is where MMDLib currently lives. Until the issues coming up out of MMDLib are resolved, adding more of the *Metals family isn't going to be helpful.

The issue with Diamonds and other materials is actually more likely that Tinkers' itself does some work in setting them up - it might be that we have to do some monkey-work to make them work. (I think we ran into a related issue in the early beta's for 1.10 and coal, actually)

Have not gotten a copy of JAOPCA and added it to the test environment - at this point it would be an added feature and we need to resolve issues with the existing features first.

ExU2 and PlusTiC were conflicting because ExU2 wanted "brittle" as a trait-name and PlusTiC wanted "heavy" - by changing the internal naming of those two to "mmd-brittle" and "mmd-heavy" the conflict went away.

**Comment by D3nnis3n** [comment]
I understand. I gave the JAOPCA dev a headsup, afaik it should be able to scan your metals without your Intervention. Maybe, he / she is willing to take a look.

I already removed all other ores from a test world and spawned Yours with cofh world and Let my friends test it. As of Now Everything works Good. They're heavily zwing them in tinkers, Mekanism and immersive engineering. We only had the Problem that thermal Expansions aluminum cannot be unified mir exchanged with your Aluminum. For nether and end ores i used an other mod and thanks to unify it will be no problem to make a Transition whenever you're done. 

Again my deepest thanks for the great mods you create. Since the beginning of metallurgy i tried to have unified ores of One mod with all Compatibility. You achieved that and thats Great.

**Comment by dshadowwolf** [comment]
One of the aims of the *metals project is to be a toolkit for pack-makers that provides what they need in a configurable manner. I'm happy this goal meshes with your needs and is working out for you.

As to the TeamCoFH Thermal family of mods - we've been trying to get a proper integration with those mods working for almost a year now. Thanks to the vagaries of how system timing work and how some things were happening in code outside our control (vanilla/Forge) there were ways things could be done that would cause BaseMetals materials to have their items/blocks show as "null" when TE started running one of its threads and show as the proper object not much later, causing massive issues.

I found, thanks to changes in 1.12, a way to - hopefully - make this work. Whether it does or not is another question entirely...

**Comment by D3nnis3n** [comment]
It is indeed working out and when Gems and minerals are ready i also will use those. There is no ore mod out there that is even nearly as complete as Yours.

As for the cofh: Only aluminum is broken, tin copper and the others work. Also mana infused ore cannot be unified to mithril, but this is due to your mod not having such an ore (well, at least for me - only ingots ans dusts, etc.) Ive been wondering for quite some time now: Why are there ores for alloys like Aluminum brass that do not exist naturally but not for mithril which in most mods is not an alloy?

**Comment by D3nnis3n** [comment]
Afaik mithril in tolkien is also an ore and not an alloy. I usually try to stay to the history or real world, e.g. i got the spawn rates like they See in Earth. Much Iron and zinc, nearly no bismuth. Mekanism ore 5x is there for s reason :D

I just decided to Not include tue alloy ores in worldgen. But i would include mithril if i could.

**Comment by D3nnis3n** [comment]
Ah, and another question: Will Modern Metals Need to be updated in order to have TiC working, too? At Beta 2.42 TiC is not working with Modern Metals, but with BaseMetals, didn't get that right before.
