### ISSUE TITLE
Aluminum OreDict

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#181]
Hello,
you might consider to add oreAluminium and oreBauxite to your Aluminum, so it works with all mods that use some kind of that. You might also consider adding oreRutile to your Titanium and the other way round - in fact, it's just the same, as Rutile is a Titanium Mineral that is used to get Titanium out of it.

Maybe this will also fix the issue that instantunify is not able to unify thermalexpansion aluminum to modernmetals aluminum, despite it being able to unify all the other ores correctly.

**Comment by dshadowwolf** [comment]
I thought this was already done - https://github.com/MinecraftModDevelopmentMods/ModernMetals/blob/master-1.12/src/main/java/com/mcmoddev/modernmetals/init/Recipes.java#L39-L43 - sets both "Aluminum" and "Bauxite"...

**Comment by D3nnis3n** [comment]
As of 2.5.0-Beta8 / modernmetals 42 the Dictionary only shows me oreAluminum. No Bauxite or Aluminium. Strange.

**Comment by D3nnis3n** [comment]
Also whats your opinion on rutile and Titanium?

**Comment by D3nnis3n** [comment]
Oh well, nevermind, i found a mod that indeed does Process titanium out of rutile. It would fuck that up to oredict them.

**Comment by dshadowwolf** [comment]
In ModernMetals there is an alloy blend of Rutile and Magnesium that produces Titanium. Otherwise you get a refined Rutile - I blame @jriwanek for that one :)
