### ISSUE TITLE
Mithril Alloying not working

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#185]
I got reported that alloying mithril is not possible, neither through dusts nor through tinkers construct. Also there is no mithril ore - therefore mithril is not craftable at the Moment. 2.5.0-Beta2.8

**Comment by dshadowwolf** [comment]
...I think this is due to an issue with the new JSON recipe system. It's on the list.

**Comment by D3nnis3n** [comment]
Yes, JEI is also showing a weird texture missing interface when pressing r.

**Comment by dshadowwolf** [comment]
Unable to reproduce without even touching the JSON for it. 1 Silver Dust, 1 Cold Iron Dust, 1 Mercury Ingot/droplet  (ie: dustSilver, dustColdiron, ingotMercury) - it's a shapeless ore-dictionaried recipe

And the Mithril Blend cooked to "Mana Infused" ingots in a TE redstone furnace.

**Comment by D3nnis3n** [comment]
Ah, you write in your curseforge page that Two silver are needed and it has
no recipe in JEI. I will look into it again and report back.

You might want to correct this:
>> Mithril is an alloy of alloy of silver, mercury, and cold-iron (2:1:1 ratio). 
This would mean 2 silver dusts, 1 Mercury blob, 1 cold-iron dust.

You are using 1 silver dust, 1 cold iron dust, 1 Mercury droplet / Ingot, what seems to be 1:1:1

Sorry for my bad german Auto correcting -.-

Am 22.09.2017 07:20 schrieb "dshadowwolf" <notifications@github.com>:

**Comment by dshadowwolf** [comment]
Ah, okay, no, that's my mistake - and I also don't see the blend recipe being missing. There is an issue because of some errors in the tool I used to make the recipes, but...

**Comment by D3nnis3n** [comment]
Okay, Mithril as powder-alloy is fixed as of 2.5.0-Beta-2.9, it was broken in Beta-2.8 - what did you do? 🗡 It has an recipe for the dusts in JEI. But no recipe for tinkers alloying.

But, it's alloying is not working in the tinkers smeltery - all other alloys do.

Also, a question: How to create Galvanized Steel and Stainless Steel in Modern Metals? Those are alloys, aren't they - even though they can be generated as ores.

**Comment by dshadowwolf** [comment]
ehhh... that is actually a bug (the "alloys generating as ores") - We were doing a lot of work in cleaning up the internals, streamlining stuff so we had fewer points of failure and removing un-needed extra data and we kinda forgot to keep the ores for alloys from generating - none of the alloys are supposed to have them.

As for Galvanized Steel and Stainless Steel... Stainless uses Chrome mixed with Steel and Galvanized is, if I'm remembering correctly, Nickel and Steel.

**Comment by D3nnis3n** [comment]
I'm going to correct myself again. The recipe was there for ages, but i searched for it under "powdered mithril" not under "mithril blend" - sorry, my fault. But i can confirm alloying in tinker does not work and i think this has to do with the Mercury being a blob that is shown as 144 mb instead of an Ingot. I got you a screenshot.

https://ibb.co/i9tSEQ

**Comment by dshadowwolf** [comment]
Yep - it is a blob. And... should be easy enough to fix. First, though, there are some updates needed in ModernMetals to get the integrations there functional again.

(maybe in 7 or 8 hours when I've had some sleep - just noticed that it's nearly 0200 here... and as you seem to be a native German speaker, I'm guessing you're around 0800 or 0900, so... it's time for me to go crawl into bed)

**Comment by D3nnis3n** [comment]
Sure, that's fine. Just wanted to tell you, so you know - if you didn't already. If you got a public list of Bugs you already know and you would be willing to share, i would look up there before posting - would that be good for you?

**Comment by dshadowwolf** [comment]
I've got a little notepad next to me, currently on the print-bed of my RepRap :)

**Comment by D3nnis3n** [comment]
As soon as modern metals works with tic and mekanism i'll test and if it works i consider it stable enough for our production Server that is full of beta mods anyways. If something goes wrong i usually know what to do. This will give some more. testing to more players, so i can Report those Little Errors that only come to Knowledge when someone does something others never do 🗡 

Haha, yeh, it's hard for me to see your Notepad :D

**Comment by D3nnis3n** [comment]
Great, seems i did everything right by not including the alloys ores in my worldgen :D

**Comment by dshadowwolf** [comment]
What I need to know, really, is what recipes are showing errors, what aren't showing at all and if I've got any that don't match the existing documentation (like how I've got Mithril wrong)

**Comment by D3nnis3n** [comment]
I'll test some more with our beta-testers later today (8 am here now). But i usually get everything reported once it is live. Will you cange mithril ingame or in your documentation?

**Comment by D3nnis3n** [comment]
But i'll Need to wait anyway, there is no new mekanism-fixed build online yet :P

**Comment by D3nnis3n** [comment]
Oh, just appeared. :D

**Comment by dshadowwolf** [comment]
Still broken in Tinkers' but I spotted the reason... it's been commented out in Tinkers'

**Comment by D3nnis3n** [comment]
I suspect this happend for a reason?

**Comment by dshadowwolf** [comment]
I think its actually that I was debugging the integration at some point and had it crashing in there, so I commented it out, found it crashed elsewhere as well, fixed that and forgot to uncomment :)

**Comment by D3nnis3n** [comment]
Haha, well then it's not hard to fix, is it? :D

**Comment by dshadowwolf** [comment]
#192 should fix this

**Comment by D3nnis3n** [comment]
This is working now and recipe is now 2:1:1 for dusts and Tinkers. I dare to Close :D
