### ISSUE TITLE
Tinkers Construct Integration in Modern Metals

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#186]
While in BaseMetals Tinkers Integration is working as of 2.5.0-Beta2.8, the same is not true for ModernMetals in Version 2.5.0-Beta2.42 used in conjunction with Base Metals 2.5.0-Beta2.8

**Comment by dshadowwolf** [comment]
I will be looking into this - at the moment the special features of Cold Iron, Mithril, Star Steel and Aquarium in non-Tinkers uses (armor and weapons) are not working and this is taking priorirty. I've got this added to my list now - thanks for the report.

**Comment by D3nnis3n** [comment]
You're Welcome.

**Comment by dshadowwolf** [comment]
Should be fixed as soon as the latest PR gets merged.f

**Comment by D3nnis3n** [comment]
I'll look into that right now.
