### ISSUE TITLE
JAOPCA Support

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#189]
I already mentioned that before and the developer answered me with this:

> After checking when BaseMetals add Ore Dictionary entries, I've concluded that the issue is on their side, as JAOPCA checks the Ore Dictionary right at the end of registries for ores and BaseMetals registers their ore entries after that.
I can add a compat to ODI for this, but report this issue to them.

I crosslinked that issue to his CurseForge page.

**Comment by dshadowwolf** [comment]
We do OreDict in the init phase, at the moment, because we needed stuff registered first. I'll see about moving things around.

**Comment by D3nnis3n** [comment]
Well, he said he would be able to add compat to it, if you need to do it like you do it now.

**Comment by dshadowwolf** [comment]
The OreDictionary stuff is no major issue - just need to do OreDict for Items in the Register<Item> event handler and for Blocks in the Register<Block> handler, thats all :)

**Comment by D3nnis3n** [comment]
Okay, sounds good. :)

**Comment by dshadowwolf** [comment]
@D3nnis3n last of the -beta2 series has been released to Curse - let us know if the changes we made to the OreDictionary registration phase have fixed this, will you ?

**Comment by D3nnis3n** [comment]
Already testing. :D

**Comment by D3nnis3n** [comment]
Nope, did not fix this issue.

**Comment by D3nnis3n** [comment]
BaseMetals Blocks and Modern Metals Blocks Creative Tabs have no icon, that should be easy to fix, too?

**Comment by dshadowwolf** [comment]
yeah, there is a small bug there - haven't had time to actually look

**Comment by dshadowwolf** [comment]
JAOPCA support issues should be solved, closing this
