### ISSUE TITLE
Problems with Diamonds

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#195]
You should look over your Diamond recipes.

You got liquid buckets, but it is not possible to smelt them, you got dusts, that you can only make out of piles, which you can only make out of dusts or smelting Diamond items in the furnace which you can only make if you have dusts. oO Or my JEI is fucking up. One of those.

I am not able to make Diamond dusts out of Diamond, maybe i can with the crushing hammer, but that is not activated on my Server. Just seems like there is some work to do. Dunno - am pretty confused by this atm.

**Comment by dshadowwolf** [comment]
...yeah, I think some of the recipes go messed up - the crackhammer is supposed to be able to produce the dust, Tinkers' is supposed to produce the molten form... I'll look at this.

**Comment by D3nnis3n** [comment]
Take a look on the crusher from ic2 / mekanism for dust production. Not everyone has the hammer turned on and all your other materials are crushable by other means, too.

Will there be Diamond Tools for TiC, when melting Diamonds will be working? As of now i can't see Diamond Tools for tic.

**Comment by dshadowwolf** [comment]
Yeah... Not a big issue - I can go and add them relatively easily. I actually forgot that there were vanilla items we extended and didn't cover them. I think I also forgot to add the checks for "is this actually available" to Mekanism and IC2 interactions for the rest.

**Comment by D3nnis3n** [comment]
Yep, that’s right. There are IC2 Items i wouldn’t Need, as it’s not installed.

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Sonntag, 24. September 2017 06:19
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] Problems with Diamonds(#195)

Yeah... Not a big issue - I can go and add them relatively easily. I actually forgot that there were vanilla items we extended and didn't cover them. I think I also forgot to add the checks for "is this actually available" to Mekanism and IC2 interactions for the rest.

**Comment by dshadowwolf** [comment]
Now that I've had a good nights sleep and fought with Forge a bit (see https://github.com/MinecraftForge/ForgeGradle/issues/451) I've got a fix in testing for this right now.

**Comment by dshadowwolf** [comment]
Fixed in #197 - closing
