### ISSUE TITLE
Issue when launching Minecraft with basemetals/modernmetals/Orespawn loaded as a mod

### ISSUE THREAD

**Issue by TSBIceLizard** [MinecraftModDevelopmentMods/BaseMetals#200]
Minecraft crashes during launch with basemetals/modernmetals and Orespawn loaded, the log file is included here.
[fml-client-latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1338143/fml-client-latest.log)

**Comment by dshadowwolf** [comment]
User error - User used the old 1.10 versions

Don't use the big, green "Download" button on CF, people, please! That gets the latest "release" version - which is 2.4.0 for Minecraft 1.10. If you're wanting the later versions, you have to actually scroll down the page - or go to the "files" part - and use the links there.
