### ISSUE TITLE
[Nether Metals] Block Explosion

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#206]
I set the Chance for Explosion to 100 and mined 50 Blocks (that i did place myself), but no Explosion.

Does it need to be generated by the world? Will it work with CofHWorld then?

**Comment by dshadowwolf** [comment]
...and it seems the event handler wasn't being registered - that's been fixed, new version will be on the Maven as soon as Jenkins finishes

**Comment by D3nnis3n** [comment]
Issue persists in Beta .3

**Comment by dshadowwolf** [comment]
hrm... fix should be in from MMDLib/BaseMetals side... lets test...

**Comment by D3nnis3n** [comment]
I’m doing this right now, then i go to bed *g*

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Donnerstag, 28. September 2017 07:54
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] [Nether Metals] BlockExplosion (#206)

hrm... fix should be in from MMDLib/BaseMetals side... lets test...

**Comment by D3nnis3n** [comment]
Well, no. Still only working for NetherQuartz – not for the other metals.
Also, it seems like some of your materials now got traits! But adamantine has None, as far as i could see. Also a lot of others – but that might be because they just don’t have some.
For me it’s bed time. Cya.

Gesendet von Mail für Windows 10

Von: dshadowwolf
Gesendet: Donnerstag, 28. September 2017 07:54
An: MinecraftModDevelopmentMods/BaseMetals
Cc: D3nnis3n; Author
Betreff: Re: [MinecraftModDevelopmentMods/BaseMetals] [Nether Metals] BlockExplosion (#206)

hrm... fix should be in from MMDLib/BaseMetals side... lets test...

**Comment by dshadowwolf** [comment]
have a push coming that fixes it - tested it myself by setting the chance to 101

**Comment by D3nnis3n** [comment]
.24? I'll look into it after some Divinity 2.

**Comment by dshadowwolf** [comment]
should be -beta1.4 of the 1.12 series :)

**Comment by D3nnis3n** [comment]
Now works for Quartz and all Nether Ores, but not for Admantine and Cold-Iron from Base Metals and Tinker's Ores (if it was supposed to do so).

**Comment by dshadowwolf** [comment]
nope - only for ores provided by Nether Metals
