### ISSUE TITLE
Crash when B:"Enable Plates"=false

### ISSUE THREAD

**Issue by Leeo97one** [MinecraftModDevelopmentMods/BaseMetals#218]
The game crashes at launch when `B:"Enable Plates"=false` in the config.
See : [crash-2017-10-09_22.04.26-client.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1369701/crash-2017-10-09_22.04.26-client.txt)

**Comment by dshadowwolf** [comment]
...logic bug in the code - somehow the guards around starsteel stuff disappeared - this is being fixed and will be in the next release (which should be part of the -beta3 series)

**Comment by dshadowwolf** [comment]
#227 should fix this

**Comment by dshadowwolf** [comment]
should be fixed by the current -beta3.49 build
