### ISSUE TITLE
[Suggestion] Base Minerals Mekanism Support

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#220]
As of now, Base Minerals seems to not have Support for Mekanism - while e.g. the Immersive Engineering Crusher can crush it into two dusts.

**Comment by dshadowwolf** [comment]
Base Minerals is not going to have any direct interfaces for ore-doubling. Other mods might catch Base Minerals materials in ore-dictionary collections, but it is not something being directly supported in this mod. Sorry.
