### ISSUE TITLE
Boron, Fluor, Beryllium and Thorium Ores

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#223]
For NuclearCraft Compatibility i'd like to see These ores in BaseMetals / Modern Metals with mekanism Support :)

**Comment by dshadowwolf** [comment]
Flourite is waiting for BaseGems, but Boron, Beryllium and Thorium are added in a PR (https://github.com/MinecraftModDevelopmentMods/ModernMetals/pull/75) and should be hitting the maven soon

**Comment by jriwanek** [comment]
Flourite should be reffed in a seperate issue
