### ISSUE TITLE
Crash on world generation when orespawn isn't loaded

### ISSUE THREAD

**Issue by tyra314** [MinecraftModDevelopmentMods/BaseMetals#238]
I get the following crash when I try to load a single player world.
The mod orespawn is not present.
I'm using BaseMetals-1.12-2.5.0-beta3.51-deobf.jar in a dev environment.

**Comment by dshadowwolf** [comment]
Yes, this is obvious - If memory serves it wasn't until after that version that BaseMetals gained a brain-dead spawn system to cover for situations like that. Try using -beta3.58 (the current dev-tip)

For most of the history BaseMetals 2.5.0 it has had a flat requirement that either OreSpawn be present or you flip the "B:using_orespawn" flag to "false" - with versions starting, I think, around -beta3.52, a fallback generator was added to cover those situations where OreSpawn was not present and you'd not changed the config flag - those versions will display a prominent message on the create world/select world screen.

**Comment by tyra314** [comment]
Sorry, me being a dumb fuck. I forgot to attach the crash report:

https://gist.github.com/tyra314/c1ba46242e293712ffeaa57c65d00b61

The issue isn't about if orespawn is there or not. The problem is, the client crashes in the function, which draws the message to the user, when you load a world, because I bet in that particular moment, there is `guiscreen == null`.

**Comment by dshadowwolf** [comment]
What the f\*ck ? There is supposed to be a "guiscreen" at that point in the client - the f\*cking selection menu that gets shown. I never tested the deobf version myself - I think all testing needs to be done in a realistic, pack-like setting - but this should not be possible.

**Comment by dshadowwolf** [comment]
Another note: @jriwanek reports using the latest releases of BaseMetals (the -beta3.58 release I suggest above) in -deobf with no issues, so this might be related to some of the problems that BaseMetals had in less than recent versions with the Horse Armor core-mod it contains, possibly among other things that have been fixed.

**Comment by tyra314** [comment]
Sorry again, I wasn't clear enough. It happens after you select a world and load it. Then the dirt background is shown with the "Loading world" or something. And on the transition between this loading into game world, this is when the crash happens.

**Comment by dshadowwolf** [comment]
...wait, what ? That... fffff - have the conditions all f*cked in there

blargh

Fix incoming

**Comment by dshadowwolf** [comment]
Fix should be on the MMD Maven soon - something like -beta3.59

Leaving this open in case you're hitting a corner that the early-out logic I added doesn't work.

**Comment by dshadowwolf** [comment]
Blargh... the Maven that hosts Hwyla is not working right now - fix build cannot happen because that goes through our Jenkins server and out

**Comment by tyra314** [comment]
Waila maven seems back. I grabbed the 3.59 build from your jenkins server, but it still happens.

https://gist.github.com/tyra314/adaf70e3d5c96c0524583470e49ca193

**Comment by dshadowwolf** [comment]
Yeah - the auto-build is failing because of issues with some of the mavens for mods we interact with not responding

**Comment by dshadowwolf** [comment]
IC2 Maven is responding again, this means we can actually get a build of Base Metals to happen...

Try this build, please - it contains the bug-fix I'd stuck in and not been able to get a build of thanks to the IC2 Maven being down...
https://maven.mcmoddev.com/com/mcmoddev/BaseMetals/1.12-2.5.0-beta3.66/

**Comment by tyra314** [comment]
Works now. Thank you.
