### ISSUE TITLE
Mekanism - Further Integration

### ISSUE THREAD

**Issue by TheSpicePhantom** [MinecraftModDevelopmentMods/BaseMetals#245]
I'd love to suggest further mekanism integration, if possible of course.

Slurry for all the metals from BMe and MMe.

**Comment by dshadowwolf** [comment]
If this isn't there, it should be. Everything that had crystals and other Mek intermediaries has the full quintupling.

**Comment by dshadowwolf** [comment]
Already done, in dev if not in released version - closing
