### ISSUE TITLE
[enhancement] Config fluid registering

### ISSUE THREAD

**Issue by Frinn38** [MinecraftModDevelopmentMods/BaseMetals#246]
Hello,

It would be great if you add an option in the config to enable/disable the molten fluids.

It could be usefull when the same fluid is added by another mod, for example molten redstone (BaseMetals) and destabilised redstone (ThermalFoundation) are conflicting and loss their textures because the 2 mods try to register the same fluid.

Thank you in advance.

**Comment by dshadowwolf** [comment]
Good idea, had been thinking of this but not actively

**Comment by dshadowwolf** [comment]
Have this ready for testing, will be adding this with part of the next patch-set I PR

**Comment by Frinn38** [comment]
Wow incredibly fast work thanks to you.
Impatient to have the next update now ^^

**Comment by jriwanek** [comment]
will be in next release
