### ISSUE TITLE
Fuel has no burn Time

### ISSUE THREAD

**Issue by BryanBoru** [MinecraftModDevelopmentMods/BaseMetals#249]
From MultiMC Log:

>[jei]: Fuel has no burn time (0): 1xitem.basemetals.wood_gear@0 basemetals:wood_gear

Running 2.5.0-beta3

**Comment by dshadowwolf** [comment]
...I didn't know we were making our wooden stuff fuels - looks like I'll have to add this.

**Comment by BryanBoru** [comment]
Didn't know either, just happened to notice it in my log and figured I'd share. Cheers
