### ISSUE TITLE
[1.12.2, latest] Can't interact with blacksmith villagers

### ISSUE THREAD

**Issue by AugiteSoul** [MinecraftModDevelopmentMods/BaseMetals#263]
I cannot open their trade window, and as you're the only mod I use that tweaks them (custom trades), I think that this is a Base Metals bug.

**Comment by dshadowwolf** [comment]
Hrm... yes - there are several issues in -beta3 regarding the villager trades code. We're working on getting a -beta4 or -rc1 out that has all the known, outstanding issues we could find proper solutions to - or find ways to repeatedly replicate the issues for testing - fixed. There will still be some outstanding, but hopefully not too many.

If you'd like a sneak-preview, see http://maven.mcmoddev.com/com/mcmoddev/ for the full span of -dev builds of the entire span of mods we offer. (Note that some, such as the "Advantage" series, have not been fully ported to 1.11 or 1.12)

**Comment by FlickySH** [comment]
In beta 4, it no longer happenes xD @AugiteSoul

**Comment by jriwanek** [comment]
Fixed in beta4
