### ISSUE TITLE
I'm new to modpack making and have this issue

### ISSUE THREAD

**Issue by RyRy1986** [MinecraftModDevelopmentMods/BaseMetals#266]
[crash-2018-02-03_12.47.05-client.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1692033/crash-2018-02-03_12.47.05-client.txt)

**Comment by dshadowwolf** [comment]
Moar Tinkers (and a few other mods) don't check if a material is already registered with Tinkers' before they try to actually register them. The solution is to either turn off the material in BaseMetals (its a config option - look in config/BaseMetals.cfg for, if memory serves, "B:EnableMithril=true" and change it to "false") or see if similar is available in Moar Tinkers.
