### ISSUE TITLE
[1.12.2] Bugs/issues relating to liquids and gasses.

### ISSUE THREAD

**Issue by Spearkiller** [MinecraftModDevelopmentMods/BaseMetals#267]
Molten Redstone and Prismarine lack a colour — they are the standard dark grey.

All Gases/slurry's are uncoloured and have the name “gas.gas(metal name here)”. Clean gasses/clean slurry's have a similar problem.

Tested on 2.5.0-beta3.51

**Comment by jriwanek** [comment]
Build 137 of beta4 should have colors for molten redstone and prismarine, the rest needs investigating still.

**Comment by jriwanek** [comment]
Should have the gasses/slurries named as of beta 5, let us know if the other issues persist

**Comment by jriwanek** [comment]
Assuming fixed as no reply in over six months, if there is still a problem, please reopen.
