### ISSUE TITLE
Crash When Disabling "Enable Small Dust" in BaseMetals.cfg

### ISSUE THREAD

**Issue by mayonnaisefarmer** [MinecraftModDevelopmentMods/BaseMetals#270]
Here's a link to the entire log, but you cannot set "Enable Small Dust" to false in the current build without inducing a crash, which is mildly inconvenient.

https://paste.ee/p/ORiyt

**Comment by FlickySH** [comment]
Is it a startup crash or a crash when entering a world? @damnsquidpeople

**Comment by FlickySH** [comment]
Hello @damnsquidpeople, Tried to reproduce the issue, but it seems fine, no crash, can you please add forge version, mc version and base metals version (im using 1.12.1 forge 14.22.1.2485 and base metals beta 4). also I am using dev environment (however tested on regular mc as well)

Aregev2

**Comment by mayonnaisefarmer** [comment]
This was on Base Metals beta3.51 and forge 14.23.2.2611 I believe, on 1.12.2, as well as it being a crash upon startup. It makes it like 5 seconds into the Forge loading screen and then crashes 100% of the time, even with just Base Metals + dependencies being the only mods

**Comment by jriwanek** [comment]
Fixed in beta4.
