### ISSUE TITLE
Just an ordinary fix 

### ISSUE THREAD

**Issue by FlickySH** [MinecraftModDevelopmentMods/BaseMetals#271]
I haven forked the project so i can not submit PRs (I think),
Anyways, when disabling the furnace cheese, the recipe is gone instead of resulting a nugget.
I fixed it, just modified the recipes class in com.mcmoddev.lib.init.Recipes.
Code: https://pastebin.com/e9XHZRwc

Aregev2

**Comment by jriwanek** [comment]
Should be fixed in dev
