### ISSUE TITLE
Crash When Placing Slab On Slab

### ISSUE THREAD

**Issue by ChloeDawn** [MinecraftModDevelopmentMods/BaseMetals#286]
Crashed when placing a gold slab on a gold slab.

**Base Metals version:** [2.5.0-beta4.145](https://minecraft.curseforge.com/projects/base-metals/files/2533182)
**MMD OreSpawn version:** [3.2.2.113](https://minecraft.curseforge.com/projects/mmd-orespawn/files/2533164)
**Forge version:** [1.12.2-14.23.2.2618](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2618/forge-1.12.2-14.23.2.2618-changelog.txt)
**Stacktrace:** [pastebin/KsUWz486](https://pastebin.com/raw/KsUWz486)

**Comment by SkyBlade1978** [comment]
#me too

[crash-2018-03-03_13.08.12-client.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/1777494/crash-2018-03-03_13.08.12-client.txt)

**Comment by jriwanek** [comment]
fixed in dev
