### ISSUE TITLE
Multi-tiered Block breaking recipes also drops lower tiered results 

### ISSUE THREAD

**Issue by Justfines** [MinecraftModDevelopmentMods/BaseMetals#30]
Tested in The ModPack: Bevo's Superstition

Forge: 1.10.2-12.18.3.2185
Base Metals version: 2.4.0.11

Visual demonstration at: [youtu.be/qs85rbfhGbs](url)

When breaking Cobblestone with a Crack Hammer in the main hand, and the Cobblestone in the off-hand, while simultaneously holding the Place block, and the Break block Key-binds, the Cobblestone when broken will drop both Gravel, and Gravel's respective hammering recipe: Sand.

**Comment by dshadowwolf** [comment]
Deeper issue than just a bug. Hammer right-click on dropped items hammers the item stacks. This is meant for some recipes, but not all of them. Resolving this such that the right-click use doesn't trigger for gravel->sand or ore->dust will require some reworking of how the Crackhammer stores its recipes and utilizes them.

This will be easier to solve post 2.5.0.  This isn't a "wont fix", just a "can't fix right now".

**Comment by dshadowwolf** [comment]
Okay - after a lot more investigation this isn't a bug at all. What is happening is the system is picking up the freshly dropped tier and using them as input. There is no way to really fix this.
