### ISSUE TITLE
Ores not spawning even with mmd orespawn

### ISSUE THREAD

**Issue by geodeheart** [MinecraftModDevelopmentMods/BaseMetals#307]
Mod-list is:
-Base Metals
-Baubles
-CodeChickenLib
-Mr Crayfish's furniture
-Inventory tweaks
-jei
-mantle
-NEI
-Optifine
-MMD orespawn
-simplecore
-simpleores
-Tconstruct
-treecapitator
-xaeros minimap

Removing simplecore and simpleores yields only the dissapearance of the metals added to the game by those mods.

**Comment by dshadowwolf** [comment]
Without knowing the versions, it is impossible to reproduce the issue and figure out the cause. This includes the Minecraft and Forge versions as well as the specific versions of the mods.

**Comment by geodeheart** [comment]
forge version is 1.12.2-14.23.2.2611

versions of mods, in same order as listed above are:
1.12-2.5.0-beta4.145
1.12-1.5.2
1.12.2-3.1.5.331
4.1.5-1.12.2
1.63
1.12.2-4.8.5.147
1.12-1.3.1.21
1.12-2.4.0.231
1.12.2_HD_U_C8
1.12.2-3.2.2.133
1.12.2-1.6.0.6
1.12.2-1.11.1.9
1.12.2-2.9.1.65
1.12-at_0.9a
1.14.8_Forge_1.12

**Comment by dshadowwolf** [comment]
Okay... I think we've actually got this solved in -dev - the basic issue is that there is an error in the handling of the older format configs (OreSpawn 3, format version 1, 1.1 and 1.2) with the latest OreSpawn. We've fixed this by upgrading the configs to version 2.0 across the board. You can find documentation on the format on the [OreSpawn 3 github wiki](https://github.com/MinecraftModDevelopmentMods/OreSpawn/wiki/OreSpawn-3-JSON-Documentation). For already fixed configs, I'll let @jriwanek answer, as she has a list of links for them maintained somewhere (I think on the MMD Discord, but don't know for certain)

**Comment by jriwanek** [comment]
https://raw.githubusercontent.com/MinecraftModDevelopmentMods/OreSpawn/master-1.12/src/main/resources/assets/orespawn/configs/orespawn.json
https://raw.githubusercontent.com/MinecraftModDevelopmentMods/BaseMinerals/master-1.12/src/main/resources/assets/baseminerals/orespawn/baseminerals.json
https://raw.githubusercontent.com/MinecraftModDevelopmentMods/BaseMetals/master-1.12/src/main/resources/assets/basemetals/orespawn/basemetals.json
https://raw.githubusercontent.com/MinecraftModDevelopmentMods/ModernMetals/master-1.12/src/main/resources/assets/modernmetals/orespawn/modernmetals.json
https://gist.githubusercontent.com/jriwanek/2a14421bee2b31a4fe43e1737b717c5f/raw/19ed588ce827477ac881d8574429ce6abef486f5/endmetals.json
https://gist.githubusercontent.com/jriwanek/333fbc24b6417fc9dc84d39e39c8139c/raw/8291305ae2eec17a8db50f59bcee93b59a0d3247/nethermetals.json
https://gist.githubusercontent.com/jriwanek/23df166c68482c7a70dff518ab50c6ff/raw/eb5b7ba36ade2f385802b52e33f5ca37ad3512fa/poweradvantage.json
https://gist.githubusercontent.com/jriwanek/12921192d63ddec0a4a4dd11370349b9/raw/beb42e613cb56614f43b84cde21b69bd973ec1c5/electricadvantage.json

**Comment by geodeheart** [comment]
Well after playing for a little bit without changing the configs I discovered that the nether ores were spawning just fine, the same after changing them but still no ores in the overworld. going to try adding "0" to the dimensions array.

**Comment by geodeheart** [comment]
It fixed it 
``` json
"dimensions": [0],
```
It turns out the empty array doesn't cause it to spawn in just the overworld.

**Comment by dshadowwolf** [comment]
Okay, strange - our test server runs the mods with some updated values in the configs (trying to bring things more into line with vanilla and where other mods want stuff as far as number of spawns and such) and these have 
```json
"dimensions": [],
```
as the dimension entries - and they work.

**Comment by geodeheart** [comment]
Well I don't know why I had to change it then, perhaps it has something to do with you running it in a server environment vs a client environment. I don't really know that much about it.

**Comment by dshadowwolf** [comment]
Oh, wait... "Just the Overworld"... spotted a key phrase there. Yes, you need to directly specify "Dimension 0" if you only want it in "the overworld" and not "all dimensions not the Nether or the End"

**Comment by jriwanek** [comment]
Is this still a problem? @geodeheart

**Comment by dshadowwolf** [comment]
@jriwanek likely not - the key phrase in the report became "just the overworld" - so tagging it as just, specifically, "dimension 0", will fix that issue

**Comment by jriwanek** [comment]
Author can reopen if it is.
