### ISSUE TITLE
well is not an issue but is pretty annoying

### ISSUE THREAD

**Issue by wickeddeamon** [MinecraftModDevelopmentMods/BaseMetals#309]
when you set to false some ores in the world generation you find a lot of holes left behind from missing   ores, its just an info, if you could fix in a small patch it would be appreciated. Nice mods btw:D

**Comment by dshadowwolf** [comment]
Yeah... OreSpawn has checks for this, but it still happens... I need to make sure the checks are actually run

**Comment by wickeddeamon** [comment]
👍

**Comment by dshadowwolf** [comment]
And... should be fixed in -dev
