### ISSUE TITLE
Horse armor broken texture

### ISSUE THREAD

**Issue by geodeheart** [MinecraftModDevelopmentMods/BaseMetals#314]
I crafted myself a set of steel horse armor and put it on my horse, but to my surprise: 
![2018-03-30_13 16 29](https://user-images.githubusercontent.com/37167944/38150693-6e1ebe56-341d-11e8-8727-0783540503dc.png)
![2018-03-30_13 16 20](https://user-images.githubusercontent.com/37167944/38150695-7181af18-341d-11e8-9808-f8e8783dad11.png)
Not sure if this is an unknown issue or simply something unfinished I stumbled upon. 
my base metals version is 2.5.0-beta5

**Comment by jriwanek** [comment]
Thanks to @Aedda that's fixed in dev now.

**Comment by jriwanek** [comment]
Oh, just for my own reference because we get so little feedback on the Horse Armor, that's with forge 2592 or later, right? (Not related to problem, more just checking so I know our recent code changes actually worked right)

**Comment by geodeheart** [comment]
that's right, forge 2611, I love how fast this team replies, thanks.

**Comment by jriwanek** [comment]
We aim to please. (:

**Comment by geodeheart** [comment]
so to fix the issue on my end I have to do what?

**Comment by jriwanek** [comment]
You can either use the releases on the maven (https://maven.mcmoddev.com) or wait for the next release.

**Comment by geodeheart** [comment]
I'll wait, the maven directory system gives me a headache. thanks again.

**Comment by jriwanek** [comment]
Shouldn't be too long:tm:, next release will either be beta6 or RC1 and come alongside the updates for 1.10.2 and 1.11.2
