### ISSUE TITLE
Disabling Certain Metals gives Blacksmith Villagers Blank Trades

### ISSUE THREAD

**Issue by Ghostrider231** [MinecraftModDevelopmentMods/BaseMetals#323]
I've heard this mod adds more trades for it's metals, but no options to disable it at the moment?

Disabling a metal while this adds more trades to blacksmith villager doesn't actually exempt those from being added.

Whenever I disable a metal for example, let's say mercury, the Blacksmith Villagers can spawn with the offers for that metal (which said metal was disabled) can end up offering you nothing/blank in exchange for emeralds. Although if you try to offer emeralds for that non-existent metal, the trader will always refuse to sell you the non-existent metal that was disabled.

Furthermore, this tends to cause an annoyance for the player when trying to scroll through all of the blank trades.

**Comment by jriwanek** [comment]
Intended to fix for next release, are you also after an option to entirely disable villager trades?

**Comment by Ghostrider231** [comment]
I'm only after for the option that introduces additional trades that this mod adds.

**Comment by dshadowwolf** [comment]
I think this is now fixed in -dev
