### ISSUE TITLE
Crash with newest Thermal

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/BaseMetals#324]
https://pastebin.com/jUgpy1WV
https://github.com/CoFH/Feedback/issues/1051

**Comment by dshadowwolf** [comment]
...No easy way to fix this, but I'm working on some code that will allow for multiple plugins for a single mod integration and be separated by the version of the mod they are integrating with

**Comment by coldReactive** [comment]
Yeah, I'm getting the issue too: https://github.com/CoFH/Feedback/issues/1053#issuecomment-384559753

@dshadowwolf Is unidict going to cause problems if and when that happens?

**Comment by jriwanek** [comment]
For the time being, you can turn off the Thermal Expansion integration in the configs, We've been talking to king lemming and in the next release of Thermal Expansion pretty much all the integration will natively be in TE

**Comment by coldReactive** [comment]
@jriwanek In the config of BaseMetals? Or in Thermal? If in BaseMetals, via a text file or something? Since we can't really get in game if it's crashing.

**Comment by jriwanek** [comment]
BaseMetals.cfg in config

edit: that's a config file.

**Comment by dshadowwolf** [comment]
fix in -dev

**Comment by jriwanek** [comment]
fixed in beta6
