### ISSUE TITLE
Something to do with Quark...

### ISSUE THREAD

**Issue by SwordsmanJoe** [MinecraftModDevelopmentMods/BaseMetals#336]
Already narrowed the conflict down to Quark. What's going on?
crash - https://gist.github.com/SwordsmanJoe/32de569939a6f81f4a50bf0d9bd5c0bd
log - https://gist.github.com/SwordsmanJoe/6d3bf4c72086cebda0fda130e346781b

**Comment by dshadowwolf** [comment]
Yeah... I don't know - I've been running a testing server with Quark on it for a while now and haven't seen this, but I also have a massive chunk of Quark turned off.

It is rather odd and indicates some possible issue with the classloader, as it claims to be unable to find some Quark classes.

**Comment by jriwanek** [comment]
I suggest trying a newer version of autoreglib, you're like 2 versions behind (And were when you originally posted too)

Autoreglib 1.3-16 was released at the same time as the version of quark you're using, so this is far more likely an update derp than anything to do with BaseMetals, from the autoreglib 1.3-16 changelog:
- Moved in a bunch of code from Quark.

Considering quark is complaining about missing classes, that looks to be your problem.
