### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopmentMods/BaseMetals#339]
This mod does not allow you to disassemble the blocks in the ingot and it is very annoying and prevents play! it's just awful because this mod overrides all other mods and pre crafting and baking ingots and blocks from other mods work items of this mod

**Comment by jriwanek** [comment]
Minecraft version, Forge version and mod version used please.

**Comment by ghost** [comment]
1.10.2

**Comment by jriwanek** [comment]
Which blocks/ingots are you having the issue with, which forge version, which version of the mod, and as I've already asked the last two questions, where did you download the mod from?

**Comment by ghost** [comment]
version mod, forge mincraft 1.10.2 mod downloaded from the site mods a problem occurs with all the blocks of metals

**Comment by jriwanek** [comment]
You've failed to specify the actual mod version twice, the forge version twice, and what the site you downloaded it from twice, third time is the charm, try again. ACTUALLY provide the information requested this time.

**Comment by ghost** [comment]
mod  version": "2.5.0-beta4

**Comment by jriwanek** [comment]
So close, only two data points left:
Forge Version
Where you got it from.

**Comment by ghost** [comment]
the website where you downloaded https://minecraft-inside.ru/mods/21050-base-metals.html

**Comment by Morpheus1101** [comment]
What is being asked is similar to the information im showing below as an example:

Minecraft: 1.10.2
Forge: 12.18.3.2511

**Comment by jriwanek** [comment]
Ding ding, we have a winner, That's not the correct homepage for my mods:
https://minecraft.curseforge.com/projects/base-metals/files?filter-status=1&filter-game-version=2020709689%3A6170
Get it from here, don't use reposts, Official builds do NOT have this problem.

**Comment by ghost** [comment]
but I do not know how to view the forge version

**Comment by jriwanek** [comment]
Also, as you appear to speak russian, if you'd be so kind as to point out to the rest of the poor folk using their reposts where to get it from properly.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
what is the difference between Base Metals 2.5.0-beta4.238 and
BaseMetals_1.10.2-2.4.0.11

**Comment by jriwanek** [comment]
2.4.0 is the older version, 2.5.0 is the newer version, use 2.5.0 unless you have good reason, and grab OreSpawn (latest for 1.10.2) from there too.

**Comment by ghost** [comment]
the problem of the mod for the version of minecraft 1.12.2 and I need for 1.10.2

**Comment by ghost** [comment]
and the problem remained blocks are not converted into ingots using a workbench and a hammer

**Comment by jriwanek** [comment]
If by workbench, you mean crafting table, and by hammer you mean crackhammer, then that's entirely expected, you can do blocks to ingots for metals in this mod the same way as you do with minecraft's iron, or you can drop them on the floor and right click to smash them to dust with the crack hammer.

**Comment by jriwanek** [comment]
Also, there's builds there for 1.10.2, just tell the files page which version you need.

**Comment by ghost** [comment]
it does not work

**Comment by jriwanek** [comment]
Well, it worked in testing, it's worked for everyone who's used it since it was released, so it's likely caused by another mod you're using.

**Comment by ghost** [comment]
I used only this mod and it breaks into dust only vanilla blocks games iron and gold

**Comment by jriwanek** [comment]
Well, as I said, You can't put a block on a crafting table with a hammer, that is not something this mod provides, If the block to dust on the ground recipe is your issue, I shall look into that, if the crafting recipes do not work, then either it's something you're doing wrong or something else is occuring, a screenshot or short recording demonstrating the issue is now the order of the day, whichever will demonstrate the issue most clearly.

**Comment by ghost** [comment]
I throw the copper block on the ground and right  click with the crackhammer press but nothing happens

**Comment by jriwanek** [comment]
But everything else is now fine?

**Comment by ghost** [comment]
Yes

**Comment by jriwanek** [comment]
Okay, I shall look into the hammering then.

**Comment by jriwanek** [comment]
Question: Are you placing it and then breaking it or dropping it and right clicking it?

**Comment by ghost** [comment]
I tried both

**Comment by ghost** [comment]
well ?

**Comment by dshadowwolf** [comment]
Try going into BaseMetals.cfg and setting the "enforce hardness" option for crackhammers to "false" if it bothers you, because it seriously sounds like you're using a crackhammer that isn't made of a strong enough material.
