### ISSUE TITLE
why error

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopmentMods/BaseMetals#340]
when I set the value :"Enable Basics"=false and run the mod basemetals and IndusrialCraft2 then there is a crash client

**Comment by jriwanek** [comment]
That's already been fixed in development, for now, it's unlikely to be on any benefit to set it to false.

**Comment by Noob1917** [comment]
but what to do ? I need to remove blocks and ingot from the game

**Comment by jriwanek** [comment]
You'll have to wait till the next release.

**Comment by Noob1917** [comment]
how long ?

**Comment by jriwanek** [comment]
When it's ready.

**Comment by Noob1917** [comment]
can you tell me the approximate number

**Comment by jriwanek** [comment]
I did: "When it's ready", that will not magically become a number.
