### ISSUE TITLE
Strange issue with chisel and bits that may be connected to this mod

### ISSUE THREAD

**Issue by Sunconure11** [MinecraftModDevelopmentMods/BaseMetals#343]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/393

**Comment by jriwanek** [comment]
We don't make any changes to minecraft:hopper, or mess with any vanilla blocks, can you provide any more information?

**Comment by dshadowwolf** [comment]
Agreed, @jriwanek - the linked to issue doesn't indicate any code we provide in any manner. I'd like to know how the conclusion that this issue involves BaseMetals was arrived at.

**Comment by Sunconure11** [comment]
I've been working on a modpack, and I attempted to add base metals. After some deduction, it appears something with base metals was preventing me from going further. I can send over the pack in it's current state, if that will help, though it is huge.

Edit: Here is the pack, in curse instance form. https://www.dropbox.com/s/2dunforlbusfs27/CM%201.12.2-CM%20Bugfix%20Build%201.zip?dl=0

**Comment by dshadowwolf** [comment]
Investigating now, but as nothing in any of the *Metals family touches the hopper code, I don't think I'm going to find a cause in BaseMetals.

**Comment by dshadowwolf** [comment]
First thought: Why am I getting messages from Farseek about stuff more than a thousand blocks away ?
Next Thought: What is eating up processor use?
Finally: Got into the game, placed some hoppers, was unable to test farther because the game was so lagged it wasn't funny. I'm wondering if your error is because of something like having a fluid change underneath C&B despite the efforts of Bord's "WHAT" mod or possibly trying to place a hopper pointing at a c&b formed facade or similar. I won't know as I've not run into any issues relating to C&B and BaseMetals through hours of gameplay and testing - however... unless the circumstances of the crash can be reproduced so the games state can be investigated and possibly have versions of the mods with instrumentation loaded, there is little that I can do.

**Comment by Sunconure11** [comment]
The crash happens when the game initializes, so I can't use a world.

Farseek tries to place stuff from Streams rather far away. It's not exactly elegant.

I'll do some testing and see if I can find a culprit. What kinds of things should I look for in a culprit mod?

**Comment by dshadowwolf** [comment]
Okay - @Morpheus1101 has tested a lot surrounding C&B and BaseMetals in your provided pack and has not been able to replicate it - either SSP or SMP. It might be that the world you are using is corrupt in some manner but I cannot say.

Bits of Adamantine placed around a hopper: https://cdn.discordapp.com/attachments/276729982800101377/452599821304594452/2018-06-03_08.29.49.png

**Comment by Sunconure11** [comment]
Wait, I wasn't able to get in game in the first place. The game would simply throw that error at me while it was still on forge's loading screen. More specifically, in the initialization phase associated with 3/7 in the loading screen.

**Comment by Morpheus1101** [comment]
I used the pack via the link you provided and both Client and a server instance loaded quite fine. Client however i allocate 10gb of RAM, you'll need at least 8+ and i allocated 8GB of RAM to the sever instance and everything was fine

**Comment by Sunconure11** [comment]
Strange. I reinstalled base metals to the pack instance so I'm going to see what happened.

Edit: I think the base metals jar might not have installed correctly, despite grabbing from curse. It appears to be booting fine now.

**Comment by Sunconure11** [comment]
I want to request this to be re-opened. Turn on plates from base metals, and run them in the pack. The minute I did so, it triggered this error once more.

I believe it could be related to using notepad instead of notepad++ for editing, for some reason, the former likes to mess up things on me as of late.

**Comment by Morpheus1101** [comment]
When i did my initial testing, Armor was all ready enabled in BMe and as prev mentioned, Sever and Client started quite fine for me.  Have you changed anything since the pack version you linked us to?

**Comment by Morpheus1101** [comment]
I can confirm a crash does indeed occur once the plates are enabled

**Comment by dshadowwolf** [comment]
We might want to exclude them from C&B in some manner - I'll be looking into them now, to see if we fixed their issue at the same time we fixed slabs, but can make no guarantee.

**Comment by Sunconure11** [comment]
Any news regarding this?

**Comment by dshadowwolf** [comment]
I've been burned out for a while and haven't had a chance to really look - but I have a feeling I know the cause. Will look in the morning.

**Comment by dshadowwolf** [comment]
...wtf ?

Just tried getting back into this and the crash I'm getting is an NPE inside Forge itself with nothing else on the stack

So... seriously, WTF ?

**Comment by dshadowwolf** [comment]
Block ID Limit is the issue. VanillaFix hides this, but disabling VanillaFix leads to this showing up:
```Time: 10/21/18 12:34 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:293)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:279)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:112)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:778)```
Basically... you need Not Enough ID's or similar - this is not a bug in *Metals at all.
