### ISSUE TITLE
Crash With Thermal Expansion (NoSuchMethodError)

### ISSUE THREAD

**Issue by TheSurround** [MinecraftModDevelopmentMods/BaseMetals#345]
versions using : 
BaseMetals - 2.5.0-beta5.214
CoFHCore-4.5.2.19
ThermalExpansion-5.5.0.29-

cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe no longer exists in the newer version of CoFHCore

error :
java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe

caused from : com.mcmoddev.lib.integration.plugins.ThermalExpansionBase.addCompactorStorageRecipe(ThermalExpansionBase.java:54)

**Comment by Morpheus1101** [comment]
You need to edit your config and disable Thermal intergration and this will solve your issue.

**Comment by AdrianCollado** [comment]
I'm having a similar issue, though in my setup the configuration file is not being generated, and as such I cannot disable the integration.

**Comment by dshadowwolf** [comment]
We have some pre-release betas on our [maven](https://maven.mcmoddev.com/com/mcmoddev/basemetals/). They automatically turn off the Thermal* integration when its detected to be a version that has the materials built-in.

**Comment by Pythonic-Rainbow** [comment]
Is this fixed? @dshadowwolf

**Comment by dshadowwolf** [comment]
-beta6 fixes this but apparently some bugs crept in elsewhere (in Tinkers', actually, which I've been unable to trigger local)

**Comment by Pythonic-Rainbow** [comment]
@dshadowwolf The Tinker's bug means BaseMetals/ModernMetals affecting some metal's value in TiC

**Comment by jriwanek** [comment]
fixed in beta6
