### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopmentMods/BaseMetals#346]
There is coming update for 1.10.2 version?

**Comment by Morpheus1101** [comment]
Versions are being worked on, however they will be released when they are.  Keep an eye on the curse page and/or the discord for when a new version is released.

**Comment by dshadowwolf** [comment]
The next release is planned to cover 1.10.2, 1.11.2 and 1.12.2 - it is almost ready

**Comment by BobalueWP** [comment]
Did you fix the Thermal Expansion no such method error?

**Comment by jriwanek** [comment]
It's fixed in dev, and there's a workaround for current release (Just disable the TE plugin, it's not needed for newer TE anyways)
