### ISSUE TITLE
new version 

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopmentMods/BaseMetals#347]
in the new version of the mod you will make the function of turning on the craft of ingots with the help of a metal block and lworkbench????

**Comment by jriwanek** [comment]
You can already put a block into a crafting table to turn them into ingots, I'm not sure what you're asking for.

**Comment by ghost** [comment]
but  it doesn't work

**Comment by dshadowwolf** [comment]
The current release version is in the MMD Public Server pack and has no issue and the current -dev is running on our private testing server and there is no issue.

So what, exactly, is "not working" supposed to tell us ?

**Comment by ghost** [comment]
![2018-06-14_17 56 05](https://user-images.githubusercontent.com/39665944/41408633-7f70bb02-6ffd-11e8-97e5-f48d07c4cebc.png)

**Comment by KiriCattus** [comment]
It would help greatly if you specified the following things:
```
Mod Name & Version: ?
Forge Version: ?
Any Dependent Mods: ?
What you expected to happen: ?
What happened instead: ?
```
That way people can find the exact cause of the issue and assist you much better rather than being silly and just saying "Oh this doesn't work. Make it work!" for example.

**Comment by ghost** [comment]
BaseMetals 2.5.0-beta4
Forge 1.10.2
no mods except this
im a expected 9 ingots but nothing happened

**Comment by jriwanek** [comment]
And the bit after the . which follows beta4?

Edit: Actually, lets save the game of 20 million questions which will get vague answers:
Just upload your log to gists, pastebin or hastebin and link it in the issue.

**Comment by ghost** [comment]
What am I to do? how to solve this block problem ?

**Comment by KiriCattus** [comment]
Provide your logs and the full version name of the mod

**Comment by ghost** [comment]
I did not understand what logs

**Comment by dshadowwolf** [comment]
<minecraft instance>/logs/  will have dated files with names, in 1.10.2, like "fml-client-latest.log", "fml-junk-earlystartup.log" and maybe some others, depending on the launcher used.

Please note that if you are using a copy of the mod not downloaded from either our Maven or from CurseForge - that is, one that does not have the correct cryptographic signature or hash - we cannot support it or handle bugs in it as we do not know what was done to the source before it was built.

**Comment by ghost** [comment]
where to find these logs ?

**Comment by KiriCattus** [comment]
Open the folder that has the mods and config folder in it and you should see the logs folder in there too.

**Comment by ghost** [comment]
[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107016/latest.log)

**Comment by ghost** [comment]
[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107018/latest.log)
[fml-junk-earlystartup.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107019/fml-junk-earlystartup.log)
[fml-client-latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107020/fml-client-latest.log)
[bootstrapper_data.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107021/bootstrapper_data.log)
[tlaucnher_data.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/2107023/tlaucnher_data.log)

**Comment by dshadowwolf** [comment]
almost right - we need "client.log"/"fml-client-latest.log" or "debug.log"... In recent 1.12 versions of Forge "latest.log" isn't useful and it seems that in 1.10, for the version you're running, it again, is not useful

EDIT: ah, there are the rest, thanks for that :)

**Comment by ghost** [comment]
I do not have it

**Comment by dshadowwolf** [comment]
Okay, signature looks good, version is correct... hrm... odd... @jriwanek I don't have a current 1.10.2 instance - this is from our last CF release - is it possible something got munged in the recipe code ?

**Comment by dshadowwolf** [comment]
...you have a custome recipe that isn't parsing properly and is causing something else to fail (just spotted this in fml-client-latest.log)

Is there a reason you are trying to add a block to ingot recipe using the crackhammer/sledgehammer ?

**Comment by ghost** [comment]
I don't know.

**Comment by dshadowwolf** [comment]
The recipe is almost valid, but you need to do the item as, say, "ore:ingotCopper" or "basemetals:copper_ingot" (and, of course, "ore:blockCopper" or "basemetals:copper_block") -- beyond that... hrm... Did you turn off the "upgrade a shield using metal plates" and the "repair armor using metal plates" recipes?

**Comment by ghost** [comment]
I didn't turn anything off

**Comment by dshadowwolf** [comment]
Alright - points to there possibly being an issue because of the custom crackhammer recipe not working - I'm looking at the code now, please give me a few minutes

**Comment by dshadowwolf** [comment]
okay... I still cannot see where this issue is coming from, other than something causing the config system to have a fault causing recipes not to get properly registered - however, for the recipe you appear to have attempted to add, you'd want:

basemetals:copper_block->9*basemetals:copper_ingot

And... Looks like I'm going to have to do some deep debugging to see if I can figure out this issue otherwise.

**Comment by ghost** [comment]
and why there мithril ore ?

**Comment by dshadowwolf** [comment]
Completeness. Thermal Expansion 4 provides it, but only in "magic" biomes, so for completeness and to have a provider for each material that other mods add, it exists. I think we've removed it entirely in more recent versions and it might even be a bug (that I thought we'd squashed) still hiding in 1.10

**Comment by ghost** [comment]
but why don't you make it in this  ?

**Comment by dshadowwolf** [comment]
huh ?

I'm sorry, something must be getting lost in translation there as I have no idea what you mean

**Comment by ghost** [comment]
I'm talking about мithril ore

**Comment by dshadowwolf** [comment]
Ah! Okay, yeah - Issue in translation, apparently. Mithril is an alloy - mix the right materials, you get Mithril. It has some support to be generated as an ore, but it actually generating as one is not enabled - and not capable of being enabled - anywhere.

The recipe is 1 mercury blob, 2 silver dust and 1 cold-iron dust to make 3 "Mithril Blend" that can be smelted to get Mithril Ingots. Or 1 mB of cold-iron, 1 mB of mercury and 2 mB of silver in a Tinkers' Construct Smeltery to get 3 mB of mithril

**Comment by ghost** [comment]
what about the fact that I can't craft blocks?

**Comment by dshadowwolf** [comment]
is it only Mithril you are having the issue with or is it all blocks ?

**Comment by ghost** [comment]
in general all

**Comment by ghost** [comment]
that there ?

**Comment by ghost** [comment]
well as a success

**Comment by jriwanek** [comment]
Un-reproducable, abusive poster.
