### ISSUE TITLE
question ?

### ISSUE THREAD

**Issue by Adarcer** [MinecraftModDevelopmentMods/BaseMetals#349]
noticed on the page your mod requires MMD Orespawn, is that a hard dependency as all my orespawn is handled by cofh world.

**Comment by YaibaToKen** [comment]
I can answer this :D Yes and no, I believe that in previous versions it was indeed a hard dependency, though you could disable it's spawn system. The dev team intended to make it a soft dependency, allowing players to use other mods for the ore generation. Not entirely sure if that is already done or not.

**Comment by jriwanek** [comment]
@YaibaToKen Please don't answer questions if you're not sure.

@Adarcer By default in current versions it's mock-hard, you can change the config to make it soft and then use whatever worldgen you wish, although options other than orespawn are entirely manual.

**Comment by Adarcer** [comment]
thanks
