### ISSUE TITLE
integrate ores and tinkers armory

### ISSUE THREAD

**Issue by Weberling2** [MinecraftModDevelopmentMods/BaseMetals#363]
whats about to integrate tinkers armory and the ores of for example base metals and Taiga into tc?

and whats about villagers who trade these ores?

**Comment by jriwanek** [comment]
We already integrate our ores into tinkers construct.
Taiga integrates it's own stuff into Tinkers construct.
Nope, not happening on villagers who trade ores, you're welcome to use Additional Loot tables and customize for yourself on that front though.

What integration exactly do you want to see for Tinkers armory?

**Comment by dshadowwolf** [comment]
if Tinkers Armory is properly integrating itself with Tinkers' Construct then all Base Metals ores should already be included in it....

At one point (early in the -beta2/late -beta1 series for 1.10.2) we actually did some integration with Taiga. That code was... flaky and never worked quite right as Taiga was designed to integrate with Tinkers' and not have other mods integrate with it (if memory serves).

@jriwanek has given the answer already for modifying other mods villagers to add our own trades.

**Comment by dshadowwolf** [comment]
...I think you might mean "Constructs' Armory" - which has been handled. We used to integrate with Taiga and probably could again, but it was a real fragile piece of work and not really worth it.
