### ISSUE TITLE
TiC Smeltery Constantan crash

### ISSUE THREAD

**Issue by CourtArtanis** [MinecraftModDevelopmentMods/BaseMetals#364]
MC: 1.12.2
Forge: 2745
BaseMetals-1.12-2.5.0-beta5.214
NetherMetals-1.12-1.2.0-beta3.52
OreSpawn-1.12-3.3.0.136

The error report is showing a TiC error, but the error doesn't appear unless BaseMetals is installed. It corrupts the save, and you need to go into MCEdit and remove the smeltery controller to allow the world to load again.

Thermal Foundation Copper Ore + Nickel Ingot (to get Constantan) in a smeltery will cause the following crash:
https://gist.github.com/CourtArtanis/e9ad2d867f2a3bf541c2549561de95ac

Fix is to disable Basemetals.

https://github.com/SlimeKnights/TinkersConstruct/issues/3636

**Comment by dshadowwolf** [comment]
Hrm... I'll be looking into this in a bit - this is a serious issue

**Comment by dshadowwolf** [comment]
Turn off "Cupronickel" in BaseMetals - Constantan and Cupronickel have the same recipe.

**Comment by CourtArtanis** [comment]
That worked.

**Comment by dshadowwolf** [comment]
Thought as much - what happened was the TiC Smeltery Controller got confused as to what to output because it had two recipes registered with the same components.
