### ISSUE TITLE
Config not disabling items [Base Metals]{1.12.2}

### ISSUE THREAD

**Issue by Hexblood** [MinecraftModDevelopmentMods/BaseMetals#365]
I set the config for plates to false but they are still showing up in JEI. 

Also casings are still showing up too. Kind of guessing they are part of that config as well since they do not have their own config.

Mod version: 2.5.0-beta5.214
Forge version: 14.23.4.2759

**Comment by dshadowwolf** [comment]
Thank you for the report - this is probably both a recipe issue and a config system issue and needs some investigation. It's on the list for my next step after getting a new version of MMD OreSpawn out.

**Comment by dshadowwolf** [comment]
Okay, looks to be an oversight somewhere - casings should not show up if "enable modder support" is turned off - plates should not gen if "Enable Plates" is false - I've checked the code on this - but... odd, the "enable mod support" option doesn't ever seem to be checked, just set...

**Comment by YaibaToKen** [comment]
Casings are being disabled with Enable Mod Support set to false;
Plates are  being disabled with Enable Plates set to false;

So I'd say this is fixed in Dev
