### ISSUE TITLE
Can we add compatibility with Construct's Armory?

### ISSUE THREAD

**Issue by ThisJustInLocal** [MinecraftModDevelopmentMods/BaseMetals#367]
It would be really cool to have star steel enhanced armors. Just a suggestion.

**Comment by dshadowwolf** [comment]
We integrate with Tinkers' Construct already - if Constructs' Armory works with Tinkers' and uses the materials registry that Tinkers' keeps internally, this should already be happening.

**Comment by ThisJustInLocal** [comment]
But it doesn’t work for me it seems.

**Comment by dshadowwolf** [comment]
Have been discussing this - it seems that Constructs' Armory wants extra material stats beyond what Tinkers' has by default. While this is not right for the current -beta cycle (we're trying to stabilize!) this is on the list for 3.x

**Comment by brisingraerowing** [comment]
[Armory Expansion](https://minecraft.curseforge.com/projects/armory-expansion) adds support for Base Metals to CA. Traits are still WIP, but armor values work correctly (the author did state that the algorithm to create those values needs to be worked on as it can make some rather OP stuff). I do believe that ~~Content Tweaker~~ ModTweaker can be used to manually set those values, though.

**Comment by YaibaToKen** [comment]
> [Armory Expansion](https://minecraft.curseforge.com/projects/armory-expansion) adds support for Base Metals to CA. Traits are still WIP, but armor values work correctly (the author did state that the algorithm to create those values needs to be worked on as it can make some rather OP stuff). I do believe that Content Tweaker ModTweaker can be used to manually set those values, though.

[Armory Expansion](https://minecraft.curseforge.com/projects/armory-expansion) author here. I'm still looking for help with coming up with a better formula for stat generation. If the authors of Base Metals could help with those, I could easily make a PR adding stat support to Base Metals / Modern Metals for Construct's Armory :P Traits can also be added over time has the tool equivalents are available to be used as base.

**Comment by jriwanek** [comment]
Drop on by the discord (https://discord.mcmoddev.com) and we'll discuss it with ya.

**Comment by dshadowwolf** [comment]
Thanks to @YaibaToKen we now have support for Constructs' Armory in -dev
