### ISSUE TITLE
New update (2.5.0-beta6) causing crash with TiCon 

### ISSUE THREAD

**Issue by breadguyyy** [MinecraftModDevelopmentMods/BaseMetals#369]
crash on load with BaseMetals 2.5.0-beta6.280 and Tinker's Construct 2.10.1.87 (custom pack)

crashlog: https://paste.dimdev.org/iloluyabug.mccrash

**Comment by jriwanek** [comment]
Can you also upload your basemetals.cfg please?

**Comment by breadguyyy** [comment]
https://paste.dimdev.org/qewoyeraka.coffeescript

**Comment by dshadowwolf** [comment]
And... yeah, with Liquid Iron turned off we'd have an issue in the recipe code, where it assumes that it can always get at fluids for vanilla materials. This is either happening because of Invar or Steel - Invar needs liquid iron (configured off) and Steel needs liquid coal (configured off)... Easy fix - just have to put in checks and maybe have it just hit the fluid registry.

**Comment by breadguyyy** [comment]
hm okay for whatever reason vanilla material liquids were off by default when i first installed so i didnt want to mess with those but thank you

**Comment by dshadowwolf** [comment]
Re-opening as this still needs a proper fix - people should be able to turn off vanilla fluids and not have it crash.

**Comment by Hexblood** [comment]
Also getting a crash on TiCon 2.10.1.87 and BASE Metals 2.5.0-beta6.280

Crash log: https://pastebin.com/hcG80iCU
Config: https://pastebin.com/wJuaqbyV

New to pastebin so hopefully I did that right

**Comment by dshadowwolf** [comment]
Same issue... Vanilla material (Iron) disabled, Steel enabled - this is being worked on (and thank you)

**Comment by Hexblood** [comment]
Ah, then the update may be toggling it off because I know I had it on.

**Comment by Hexblood** [comment]
Still getting the crash. Re-enabled Iron, Gold, and Emerald that had been toggled off. Then tried with Diamond and Redstone enabled since also Vanilla, still crashing.

I did not get a crash downgrading to Beta5.

**Comment by jriwanek** [comment]
Okay, we'll dig deeper, for now, you can disable the TiC integration in the config and that should resolve your crash.

**Comment by YaibaToKen** [comment]
this is fixed in -dev (has been for over a week now actually <.<)
