### ISSUE TITLE
Are the armor pieces supposed to smelt to 1 ingot in the Tinkers Smeltery?

### ISSUE THREAD

**Issue by brisingraerowing** [MinecraftModDevelopmentMods/BaseMetals#370]
I noticed that the armor added by this mod will only smelt to one ingot in a Smeltery, instead of the number used to craft the piece. Is that intended?

**Comment by dshadowwolf** [comment]
...that seems like a massive error - but... I don't actually recall coding "smeltery cheese" into the mod at any point, so if its happening, its likely either a bug in our code or something going wonky inside Tinkers' itself... Together with all other issues, I'm leaning towards "DShad screwed something up again"

**Comment by YaibaToKen** [comment]
@BrisingrAerowing could I ask what metal that happened with? Fully tested copper but it smelt to the proper amount of ingots with Furnace Cheese set to true.

On further testing, it was noticed that without Furnace Cheese, you couldn't even smelt the stuff. Fixed in -dev.

**Comment by brisingraerowing** [comment]
Not in a furnace, in a Tinker's Smeltery.

**Comment by YaibaToKen** [comment]
TiC's smeltery gave the proper amount of ingots for both Copper tools and Copper armor

**Comment by dshadowwolf** [comment]
Tested with Cupronickel chestplate, Electrum leggings, Adamantine helmet and Star-Steel helmet - all came out as 1 ingot. There is something to this.

**Comment by dshadowwolf** [comment]
Working on this - have found that it appears to be a combination of things and might require some extra work to resolve if this last check doesn't work out

**Comment by dshadowwolf** [comment]
fixed in latest -dev
