### ISSUE TITLE
Unable to remove mithril blend recipe using crafttweaker

### ISSUE THREAD

**Issue by terrapin47** [MinecraftModDevelopmentMods/BaseMetals#372]
Attempting to remove the mithril blend crafting recipe via crafttweaker doesn't seem to be working.

![image](https://user-images.githubusercontent.com/13740412/46038047-0b4f1080-c0d8-11e8-9eba-b9d0d6aab1cd.png)

Here is my CT script:
```
#modloaded basemetals

// Remove unobtanium from furnace
furnace.remove(<ore:ingotMithril>, <basemetals:mithril_blend>);

// Remove mithril recipes
recipes.remove(<basemetals:mithril_blend>);
mods.jei.JEI.removeAndHide(<basemetals:mithril_blend>);
```
It is correctly hidden from JEI, but the recipe can still be seen if you hit the Show Uses key on silver dust or cold iron dust.

I have the same thing written for electrum blend, which works fine:
```
recipes.remove(<basemetals:electrum_blend>);
mods.jei.JEI.removeAndHide(<basemetals:electrum_blend>);
```

**Comment by dshadowwolf** [comment]
The CraftTweaker integration is... in major need of a rewrite, as soon as I figure out how to make it work proper. @jaredlll08 has been helpful but it seems that my brain has not been able to connect his help to how to fix the code.

**Comment by terrapin47** [comment]
Actually was a mistake on my part.
