### ISSUE TITLE
Issue with this mod and nature's compass when teleporting

### ISSUE THREAD

**Issue by Sunconure11** [MinecraftModDevelopmentMods/BaseMetals#373]
https://github.com/TheKiipster/Novam-Terram/issues/5

Note: Issue only began to fire while I was toying around with a script for In Control.

**Comment by Sunconure11** [comment]
I had also turned on sickles and plates.

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/avodedunup.mccrash

**Comment by jriwanek** [comment]
Looks like a bug with orespawn, not basemetals, thankfully you got the right people, even if you did get the wrong issue tracker.

**Comment by Sunconure11** [comment]
I believe some of the biomes from Novam Terram may be acting up, as well. @thekiipster

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/zageduzeza.mccrash

https://paste.dimdev.org/yifucejina.mccrash

**Comment by TheKiipster** [comment]
I'll check out compatibility with biomes o plenty again but maybe it could be a different mod instead? In the https://paste.dimdev.org/yifucejina.mccrash crash report I saw something with a salt mod and coherent villages could be those two mods

**Comment by dshadowwolf** [comment]
The OreSpawn bug seen is a known one that has a fix in -dev - otherwise I'm not seeing where BaseMetals is responsible for this at all. Closing.
