### ISSUE TITLE
Weird interactions with Mekanism's Chemcial Washer

### ISSUE THREAD

**Issue by Spearkiller** [MinecraftModDevelopmentMods/BaseMetals#375]
Putting an ore slurry in a chemical washer has a weird effect. With the Slurry's added by mekanism (Copper, Tin, etc) it works as normal, as it does with base metal ores, (Zinc, Adamantite, etc). However, when you put speed upgrades into the Chemical Washer, things start to get weird, with only arbitrary amounts of slurry being processed. It works as normal with no speed upgrades. With one speed upgrade you need to have 2000mb of slurry for it to be processed, With two speed upgrades you need to have 4000mb for it to be processed. Three speed upgrades needs 8000mb for it to be processed, and from 4 speed upgrades and on the Chemical Washer clogs up with slurry and doesn't function. The problem is the number of speed upgrade determines how much is processed at once, so with one speed upgrade it will only work with 2000mb in the washer, and then all 2000mb is processed at once, as opposed to having no upgrade where 1mb is processed at a time, and the speed upgrades just determine how many mb are processed per second or something, I don't know how it works. It can just be really annoying to have the entire system plug up because of a speed upgrade, even with adequate power. One could argue that I could just remove speed upgrades to get it to work but I dont believe that's how it should be :v

Also, one side note on the topic of slurrys, all base metal slurrys, regular and cleaned, are both colourless, so this is another issue that needs looking at as well :)

BaseMetals version 1.12-2.5.0-beta6.280

**Comment by dshadowwolf** [comment]
...I have no clue - this is strange, as we add it as 1000mB of input to 1000mB of output for the Chemical Washer. I'll have to ask some others about this.

**Comment by Spearkiller** [comment]
maybe you could change it to 1mb input to 1mb output, because from what it seems that's what mekanism does for its ores. That would also mean even if the user has 4 or more speed upgrades it still works because it would only require 16mb of slurry. it would also stop the system shutting down if you had like, 800mb left over somehow.

**Comment by dshadowwolf** [comment]
hrm... okay
