### ISSUE TITLE
Adamantine, being smelted as adamant

### ISSUE THREAD

**Issue by StarboundModderRWC** [MinecraftModDevelopmentMods/BaseMetals#379]
also will not crush in the Ender io sag mill.

**Comment by YaibaToKen** [comment]
Forge, BaseMetals, OreSpawn, EnderIO and it's dependencies' versions please.
Also, does it still happen with only EnderIO and BaseMetals?

**Comment by dshadowwolf** [comment]
also... if a pack is being used, the packs name - while we do register with EIO, things in the actual config files can and will override there.

**Comment by jriwanek** [comment]
@StarboundModderRWC Is this still an issue?
Issue will be closed in 30 days if no response.

**Comment by dshadowwolf** [comment]
no response in 30 days, closed
