### ISSUE TITLE
Do you have a list of...?

### ISSUE THREAD

**Issue by JadianRadiator** [MinecraftModDevelopmentMods/BaseMetals#381]
Do you have a list of color codes for the materials either in hex or convertible to hex?
I want to add Base Metals and Modern Metals metals as tools in Artisan's Workshop.
Some of them it already has, but I want to add all of the Base/Modern Metals stuff as Artisans Workshop tool material.
Also posted on [Modern Metals](https://github.com/MinecraftModDevelopmentMods/ModernMetals/issues/110), as I don't know a central place I could post for both at once.

**Comment by dshadowwolf** [comment]
It's in the code - sadly we do not have one separate, that I can find
