### ISSUE TITLE
Error on Server Startup

### ISSUE THREAD

**Issue by Problembeloeser** [MinecraftModDevelopmentMods/BaseMetals#407]
Getting an Exception on starting a server with this mod, client using same mod version and dependency mod version starting up fine

https://pastebin.com/TKFchd8f

**Comment by dshadowwolf** [comment]
Known issue, caused by Java claiming full I18n and expecting only English usage for the decimal point in some key routines. Fix queued, waiting on completion of some other work and the next release.

**Comment by Problembeloeser** [comment]
is there a workaround? Or a time schedule for the next patch? It's kinda bad if you exclude people with nonenglish pcs.

**Comment by dshadowwolf** [comment]
let me check - the only workaround, at this point, is to either set to a language that doesn't use the comma as the decimal point or that we might have something in -dev already with the fix instead of that being in the current "add another promised feature" branch

**Comment by dshadowwolf** [comment]
This should work with current releases of ModernMetals and EndMetals (note "should" - there may have been some internals changes that will conflict) but it appears the fix was included in all builds from October 21 onward, so: [Build 307 from October 23](https://maven.mcmoddev.com/com/mcmoddev/BaseMetals/1.12-2.5.0-beta6.307/)

**Comment by Problembeloeser** [comment]
Actually this does the same error, although the corresponding lines have changed, proving i did put the build u gave me. Do you got any idea where this "0,10" thing comes from? If its coming from a config file i could change it as a workaround

**Comment by YaibaToKen** [comment]
@Problembeloeser Is this happening with the default configs? And could I ask you to replace all the ',' with '.'?
This can usually be easily achieved with most text editors, telling it to replace all. That will tell you right away if it's something in the config file or if it's something internal. If replacing does indeed fix it, that will be a valid workaround for now.

**Comment by Problembeloeser** [comment]
@YaibaToKen actually i did search for the erroring term in the config but got no hit. Even searching ',' in the config yield no results other than commented lines

**Comment by dshadowwolf** [comment]
@YaibaToKen this is happening because we have a String.format("%0.2f") and that defaults to using system locale - which would format with the systems configured decimal. For a lot of countries this is the comma. Unfortunately the later Float.parseFloat() on that string fails because java.lang.Float's "parseFloat" method is not I18n compliant and does not recognize the comma as a decimal point.

Starting with the October 20 builds... fark, just noticed there is one more line that has the faulty assumption in it. Only solution, at this time, is to run Minecraft as EN_GB or EN_US - sorry - as this bug is actually ancient and nobody had reported it until after -beta6 dropped. (and we need to get someone on the team testing with non-English localization)

**Comment by Problembeloeser** [comment]
@dshadowwolf that seems like a solution, as it only affects the server where localization is nearly irrelevant, any tips on how to achieve this?

**Comment by dshadowwolf** [comment]
I have never tried, but if it's a Unix/Linux server you could try something like:
```
LOCALE=EN_US <java command>
```

**Comment by Problembeloeser** [comment]
on which level should this be used? I use the standard minecraft forge server jar to start, if there is any parameter to pass into the start script id like to use it that way

**Comment by dshadowwolf** [comment]
This is the command-line - Give me a bit to look to see how to set things like that in the java command and not as a per-process environment variable like my original suggestion there.

**Comment by dshadowwolf** [comment]
```
java -Duser.country=US -Duser.language=en <rest of command>
```
(according to StackExchange and the Oracle JVM docs)

**Comment by Problembeloeser** [comment]
Actually, this is working :D. Worth mentioning, that i learned that the order of params did matter as the error would still occur, if i appended the params to the command rather than inserting them before the actual jar name. I guess i need to pay respect for developers reacting so fast and helpful :D hope i someday will also manage such a project like a minecraft mod with compat

**Comment by YaibaToKen** [comment]
@dshadowwolf I can probably set up an old laptop to use the Portuguese locale as that will use ',' instead of '.' for decimals and test the builds

**Comment by dshadowwolf** [comment]
despite having done a run through the code for parseFloat() instances, this is still happening... re-opening

**Comment by GhostZero91** [comment]
i don't understand what i'm supposed to change.

**Comment by dshadowwolf** [comment]
When starting a server:  
`java -Duser.country=US -Duser.language=en <rest of command>`

This forces the server to use a locale where the decimal point is '.' instead of ',' - as stated elsewhere, Java is broken there

**Comment by GhostZero91** [comment]
And i'm supposed to put that text where?

**Comment by YaibaToKen** [comment]
@GhostZero91 if you're having this issue, I assume you're running a dedicated server for Minecraft. Is it self-hosted, or are you renting a server from a hosting service?

**Comment by GhostZero91** [comment]
im running dedicated, self-hosted

**Comment by YaibaToKen** [comment]
Alright, you should either have a bat file on Windows, a sh file on Linux or be running the server straight from the command-line- Either way, that is where you need to follow dshadowwolf's advice. 

> When starting a server:
> `java -Duser.country=US -Duser.language=en <rest of command>`
> 
> This forces the server to use a locale where the decimal point is '.' instead of ',' - as stated elsewhere, Java is broken there

**Comment by GhostZero91** [comment]
now im getting fatally missing registry entries

**Comment by jriwanek** [comment]
Client and server must be using the same config files.

**Comment by GhostZero91** [comment]
how do i fix it? i tried deleting server config

**Comment by jriwanek** [comment]
I literally just told you. If you're not prepared to listen, then there's nothing further we can do to assist.

**Comment by GhostZero91** [comment]
im sorry i didnt understand you

**Comment by jriwanek** [comment]
Client and server MUST be using the same config files, it's as simple as that, if you can't understand that, I'm not sure anybody can help you. Asides that, we only support the mod, not the basics of modpack making, configuring servers or how to use a computer.

**Comment by GhostZero91** [comment]
okay well thank you, im trying everything i can possibly think of, ive been using mods and minecraft servers several years and always something different shows up, anyway thank you for all the help im getting.

**Comment by jriwanek** [comment]
Well, rather than trying what you can think of, try doing what I told you to do. This issue will now be locked.
