### ISSUE TITLE
Obsidian not existing?

### ISSUE THREAD

**Issue by James-Fire** [MinecraftModDevelopmentMods/BaseMetals#408]
I can't get obsidian dust, through the use of a crack hammer on a block. I've tried diamond and adamantine, both times the block disappeared without dropping anything.

**Comment by dshadowwolf** [comment]
Since the 1.12 port we've been having recipe issues. This should have been resolved in the -beta6 release - if it wasn't, or if this isn't about the 1.12 version, please ignore me. @jriwanek handles anything that isn't "current" (ie: 1.11 and prior)

**Comment by dshadowwolf** [comment]
Unable to reproduce on current -dev - closing as resolved.
