### ISSUE TITLE
Incompatibility with Material Changer Mod (Swords Only)

### ISSUE THREAD

**Issue by Squidman13** [MinecraftModDevelopmentMods/BaseMetals#410]
While trying to use the [Material Changer](https://www.curseforge.com/minecraft/mc-mods/material-changer) Mod to change the stats for some BaseMetal materials, I came across a bug where changing the enchantability of any sword from this mod would have no effect, but it would still change the enchantability of all other tools of the same material as intended. I am using the latest version of Material Changer, which claims to have fixed a [bug](https://www.curseforge.com/minecraft/mc-mods/material-changer/changes) involving swords being unaffected by enchantability, but this does not seem like the culprit since I can still edit the enchantability of swords from vanilla and other mods just fine. The change log for Material Changer lists "Tool material targeting for swords" being the problem, so I was wondering if Base Metals has a bug causing swords not to register to their material correctly. Any information would be much appreciated.

**Comment by dshadowwolf** [comment]
Without a way to actually look at its code to see how it is doing what it is doing I don't know where to start fixing this. We actually have a very thin wrapper around vanilla for our swords, at that, so if their code works with vanilla, it should work with our tools. If it isn't then I'd need to know how they are achieving their effect so I can figure out where we are differing from vanilla on that front.
