### ISSUE TITLE
CurseForge Update

### ISSUE THREAD

**Issue by bookerthegeek** [MinecraftModDevelopmentMods/BaseMetals#415]
# Heyo...

Sorry to bother you, again. :frowning: Sadly I can not upload my pack due to an interesting curseforge [policy](https://authors.curseforge.com/knowledge-base/minecraft/3279-non-curseforge-mods).
```
If a specific version of a CurseForge-hosted mod is not on the site, this means the author has chosen not to upload it for some reason.
These versions are not allowed to be included in modpacks.
```

## So....
Any change we could get the following pushed to CurseForge please?
- BaseMetals-1.12-2.5.0-beta6.308.jar
- BaseMinerals-1.12-2.5.0-beta6.58.jar
- EndMetals-1.12-1.2.0-beta4.55.jar
- ModernMetals-1.12-2.5.0-beta6.142.jar
- NetherMetals-1.12-1.2.0-beta4.66.jar

### Anywise...
Thank you for your time and these great mods. I look forward to seeing what you come up with next. Also the discord link on the project pages on curseforge is expired otherwise I would have brought this up their.

**Comment by dshadowwolf** [comment]
Let me as @jriwanek

**Comment by jriwanek** [comment]
We'll be preparing a release over the next few days.

**Comment by dshadowwolf** [comment]
Release on CurseForge - look for -beta7 for BaseMetals, BaseMinerals and ModernMetals, -beta4.56 (gah! I didn't get the number updated there - should be -beta5) for EndMetals and -beta5 for NetherMetals

**Comment by bookerthegeek** [comment]
Thank you good sirs!
