### ISSUE TITLE
BaseMetals 2.5.0-beta7.311 crashes on server forge build 2808

### ISSUE THREAD

**Issue by pkej** [MinecraftModDevelopmentMods/BaseMetals#418]
Here is the crash-report: https://gist.github.com/pkej/9a734c40d5d16981281b368696879502

**Comment by pkej** [comment]
Pressed enter and had it close on me :)

**Comment by linuskr** [comment]
This seems to be a locale issue similar to #378. I don't get the point of the float -> String -> float conversion though ...

**Comment by dshadowwolf** [comment]
should be fixed in -dev. Closing.
