### ISSUE TITLE
could this,modern, or orespawn mess with villager spawning

### ISSUE THREAD

**Issue by Thesmartone7** [MinecraftModDevelopmentMods/BaseMetals#421]
so i installed this with and orespawn and modern metals and while i doubt its your mod(s) doing this, its either this or tinkers, but could anything in this mod conflict with a mod like torocraft or minecraft comes alive to make villagers keep spawning forever within a village..like absurd numbers of villagers just...appearing?

**Comment by dshadowwolf** [comment]
The only thing done with villagers is the addition of some trades to the blacksmith.
