### ISSUE TITLE
Obsidian Door Recipe Error

### ISSUE THREAD

**Issue by Hexblood** [MinecraftModDevelopmentMods/BaseMetals#437]
Minecraft version: 1.12.2
Forge version: 14.23.5.2836
Base Metals version: 1.12-2.5.0-rc1.322

Issue:

Obsidian Door currently has the same recipe as the Obsidian Trapdoor. The bottom two ingots are missing from the recipe. Recipe defaults to the output the Door. I can access the Trapdoor via the mod "No Recipe Conflict."

**Comment by dshadowwolf** [comment]
thanks for the report - this might already be fixed in -dev but I'll look anyway

**Comment by dshadowwolf** [comment]
alright, fixed in -dev - still don't know how that happened, but... fixed :)
