### ISSUE TITLE
Fatally missing registry entries

### ISSUE THREAD

**Issue by msglm** [MinecraftModDevelopmentMods/BaseMetals#452]
On Joining a server with BaseMetals installed, the error Fatally missing registry entries disconnects anyone joining.  

Client log
[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3488206/latest.log)
Server Log
[latest (2).log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3488208/latest.2.log)

**Comment by jriwanek** [comment]
are you using the same configs on client and server?

**Comment by msglm** [comment]
need to ask host, will be a little bit before I get an answer

**Comment by jriwanek** [comment]
While you're at it, ask for FULL logs. The ones you've provided are incomplete and amongst other things are missing the mod version info.

**Comment by msglm** [comment]
Client Log
[debug-1.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3488317/debug-1.log)
The server host is still not back, but I have the full log file from my client.  
![image](https://user-images.githubusercontent.com/32282125/62814816-a7a7b900-bad8-11e9-8806-fe8bec968bba.png)
Here is an image of my mod folder, will post download links for any mods requested.

**Comment by msglm** [comment]
sorry, forgot to mention I was also running end metals, nether metals, modern metals, and of course, base metals.

**Comment by dshadowwolf** [comment]
heh, I'll look into this, as it isn't something I've seen - the only issue (and one I'll be checking) is that it seems the mmdlib you've got isn't signed. That might be a mistake on our end, though.

Note that I don't have a lot of free time at the moment and there is a lot that has accrued as needing done for the -rc3 release, so hopefully some of the rest of the team can pitch in, but we're all rather overloaded with both RL concerns and the modding.

**Comment by msglm** [comment]
Understandable, will work with our host to see if it's a client issue, I suspect it is.

**Comment by msglm** [comment]
The issue was with the server's config, as expected. Issue resolved.

**Comment by CowHItFace** [comment]
Is there a way for you to find out, what exacly the server owner change? I have the same Situation with my server at the moment but i dont know what to change and what not....

**Comment by dshadowwolf** [comment]
@CowHItFace there are numerous tools for performing a "diff" to find what is different - you can use one of them to compare the files and find what is different
