### ISSUE TITLE
Server-side exception, AquariumProperty implicated

### ISSUE THREAD

**Issue by miiichael** [MinecraftModDevelopmentMods/BaseMetals#458]
Hi folks,

I run a modded 1.12.2 server, with forge 14.23.5.2838, MMDLib 1.0.0-rc2, Base Metals 2.5.0-rc2, and [a bunch](https://minecraft.deegan.id.au/modpack/polytopia19-modlist.txt) of other mods.

A player reports repeated disconnections, requiring me to nuke his player file in order to reconnect successfully. I found [this error](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3721749/error.txt) in the server log. It's likely that it all goes horribly wrong just as he completes his set of Aquarium armour...

**Comment by dshadowwolf** [comment]
Tracked it down, am in the process of fixing this - turns out that the way we've been getting the "Minecraft World" is broken for server-side use as it gets a reference to a "WorldClient" instance - which is client-only code. Oops.

**Comment by dshadowwolf** [comment]
okay, PR #459 should fix it - that is waiting on a fix for the Travis CI to go in so the code gets all the needed testing.
