### ISSUE TITLE
Forge Server crash with only base metals and MMDlib mods.

### ISSUE THREAD

**Issue by xdPrzemo** [MinecraftModDevelopmentMods/BaseMetals#460]
Hey guys I have problem with base metals mod.
This mod crashing my forge server.
I use: 
BaseMetals-1.12-2.5.0-rc2.332
MMDLib-1.12-1.0.0-rc2.36
OreSpawn-1.12-3.3.1.172

[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3747855/latest.log)
[debug.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3747856/debug.log)
[crash-2019-10-20_14.35.31-server.txt](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3747857/crash-2019-10-20_14.35.31-server.txt)

**Comment by dshadowwolf** [comment]
parseFloat crash - see #378 - this is fixed in the -dev series, see http://maven.mcmoddev.com/com/mcmoddev/ for the -dev versions.

**Comment by xdPrzemo** [comment]
Not working 
Who version I should download to forge-1.12.2-14.23.5.2847?

**Comment by xdPrzemo** [comment]
![Action 2019-10-20 17-47-33 mp4 (0_00_17) 000000](https://user-images.githubusercontent.com/56789398/67162219-431f9a80-f362-11e9-9cde-8b95e460708b.png)

**Comment by dshadowwolf** [comment]
hrm... This is a new one on me - looks to be client-only code getting called server side. I have not seen this in testing.

**Comment by SkyBlade1978** [comment]
@xdPrzemo do you use discord? it might be easier to diagnose the issue id we can speak with you in real time..

**Comment by xdPrzemo** [comment]
Yes I have discord but I don't know if I speak english enough to speaking.
But I want try

**Comment by xdPrzemo** [comment]
I uploaded my server on Zippyshare
https://www94.zippyshare.com/v/G6uxDTDO/file.html

**Comment by SkyBlade1978** [comment]
This is our public discord server; 

https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fdiscord.mcmoddev.com%252f

And you would want the channel #metals-minerals-gems

**Comment by dshadowwolf** [comment]
combination of poor instructions (on my part) and user error triggered the later crash/inability to start. Resolved.
