### ISSUE TITLE
[Suggestion] Add config option to use arrows for crossbows.

### ISSUE THREAD

**Issue by Xonok** [MinecraftModDevelopmentMods/BaseMetals#481]
Newer versions of minecraft use arrows for both bows and crossbows. I think that's a good idea, because crossbow bolts are not fundamentally different from arrows in how they're used. 
Having them as separate items means having to duplicate a large amount of items. E.g, enchanted bolts vs enchanted arrows - Same basic thing.

Therefore I propose that either crossbow bolts should be removed entirely in favor of arrows, or at least that there should be a config option which removes all bolts and makes crossbows use arrows instead.

**Comment by dshadowwolf** [comment]
The 1.16 and later releases _will_ do this, without a config option. For older versions we try to maintain continuity and behavior.
