### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Kasia1403** [MinecraftModDevelopmentMods/BaseMetals#482]
Light glitches, mushrooms in air and player can't move. I'm using MC 1.12.2 Forge 14.23.5.2860 and Base Metals - BaseMetals-1.12-2.5.0-rc2.332.jar. Tested with previous version and still the same.

**Comment by Kasia1403** [comment]
https://www.mediafire.com/file/s6juvohtrclm7xy/1.12.2_test_will_work_hopefully.zip/file

**Comment by TheCurle** [comment]
Why did you send a random zip with no context or meaning?
You've not given us any information that would be useful for debugging any of this.
Please apply brain and help us out here.

**Comment by Kasia1403** [comment]
I can't get a crash report.

**Comment by TheCurle** [comment]
Well yes. if it doesn't crash there's no report. That's not what i asked for, though. 
I asked for information that would help us debug "light glitches", such as pictures.
Or "mushrooms in air", such as pictures.
Or "player can't move", such as what the hell that means, or pictures.

**Comment by Kasia1403** [comment]
Could You just run my modpack and create a new world and see everything ?

**Comment by TheCurle** [comment]
I'm running Base Metals on its own (with the dependent libraries) and i'm not seeing any of these issues, so i'm going to have to assume that, if you won't cooperate, the issue isn't Base Metals.

This issue tracker isn't tech support for random modpacks.

**Comment by Kasia1403** [comment]
I forgot one thing - if You run chunk pregeneration then theese glitches disappear, but only in pregenerated chunks. Is it at least a little helpful ?

**Comment by TheCurle** [comment]
No.

**Comment by Kasia1403** [comment]
Why in Minecraft Forum they wanted me to disable Base Metals and Base Minerals and do the test without theese mods ?

**Comment by TheCurle** [comment]
Ask them, not me.

**Comment by SkyBlade1978** [comment]
Due to the way base metals works and what it does, it is remarkably unlikely to be connected with the symptoms you describe.

The mod, in laymen's terms creates new types of metal ores, places them underground for mining, and items which can be crafted from them.

For example, unusual visual effects are more likely a product of a shader pack, base metals doesn't have anything to do with mushrooms, or interact with the players ability to move.

It sounds like you have issues elsewhere in your mod pack.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dshadowwolf** [comment]
Quite technically if there are _any_ issues with generation from BaseMetals and the "Fallback Generator" isn't in use, then it isn't doing any world-gen itself and is not to blame for any of the issues. BaseMetals and friends use MMD OreSpawn (latest is somewhere around version 3.3 or 3.4) to do all world-generation.

If you are not using the fallback generator or MMD OreSpawn, then _no_ MMD mods are doing _any_ world-generation.
