### ISSUE TITLE
IC2 Plugin

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopmentMods/BaseMetals#64]
dustTiny<OreName> "Tiny Pile of <OreName> Dust"
plateDense<OreName> "Dense <OreName> Plate"
crushed<OreName> "Crushed <OreName> Ore"
crushedPurified<OreName> "Purified Crushed <OreName> Ore"

Uranium & Plutonium need better integration most likely

**Comment by dshadowwolf** [comment]
Need to add grid-recipes using the forge hammer yet, but this is mostly complete

**Comment by dshadowwolf** [comment]
Crafting Grid forge-hammer recipes require a custom recipe class to be created and the IC2 "advanced recipes" API (ic2.api.recipe.Recipes.advRecipes) is broken at this time

**Comment by dshadowwolf** [comment]
With PR #292 this is, basically, complete and the only IC2 machine we could interact with but do not, at this point, is the Block Cutting machine - and adding that should be relatively easy now.
