### ISSUE TITLE
Finish JSON work

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopmentMods/BaseMetals#87]
As described

**Comment by Cazsius** [comment]
Localizations Done

**Comment by Cazsius** [comment]
Had to revert

**Comment by dshadowwolf** [comment]
#227 might mark the end of this on the JSON side - is the localization work done ?

**Comment by jriwanek** [comment]
No further issues with the JSON found in BMe or MMe, time to open a new issue if more found
